package com.sellerops.review.publish.cafe24;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.sellerops.connector.cafe24.Cafe24HttpClient;
import com.sellerops.connector.cafe24.Cafe24WriteApprovalRequired;
import java.net.URI;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The ONE write of the review lane: {@code POST /api/v2/admin/boards/{board_no}/articles/{article_no}/comments}
 * ({@code docs/vendor/cafe24-admin-api/post-boards-articles-comments.md}, scope
 * {@code mall.write_community}) — a shop comment under a 구매후기 article.
 *
 * <p><b>The second write client this connector has, and the only file that may hold it.</b>
 * {@code Cafe24BoardCommentsClient} stays READ-only (its structural test says so); this class spells
 * the POST, and a structural test in this package pins that no other production file posts to a
 * {@code /comments} resource.
 *
 * <p><b>One call, and never twice</b> — the same discipline as {@code Cafe24ReplyArticleClient}, for
 * the same reason: a transport ambiguity returns {@link Outcome.Kind#UNKNOWN} because a comment may
 * already exist under a customer's review and a second POST is a second public reply, not a retry.
 *
 * <p><b>Two interlocks before a byte leaves.</b> The write grant is the caller's check; this class
 * refuses any non-offline host without an armed live-run approval id
 * ({@code sellerops.review.publish.cafe24.live-approval-id}).
 *
 * <p><b>Nothing person-shaped is invented.</b> {@code writer}/{@code member_id} are the connection's
 * {@code mall_id} (the contract's documented 상점명-rendering condition), {@code password} is the
 * per-comment secret of outcome A — generated by the caller, sent once, never kept — and no other
 * field is sent: {@code rating} is omitted (a default of 0 is the platform's, and a shop does not
 * rate its own reply), {@code secret} is {@code F}, and {@code client_ip} is not a parameter here.
 */
public class Cafe24ReviewCommentClient {

    private static final Pattern MALL_ID_SHAPE = Pattern.compile("[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?");
    private static final Set<String> LOOPBACK_HOSTS = Set.of("localhost", "127.0.0.1", "::1", "[::1]");
    /** The contract's bounds on {@code password}. */
    static final int PASSWORD_MIN = 1;
    static final int PASSWORD_MAX = 20;
    /** The contract's bound on {@code writer}. */
    static final int WRITER_MAX = 100;

    private static final Logger log = LoggerFactory.getLogger(Cafe24ReviewCommentClient.class);

    private final Cafe24HttpClient http;
    private final ObjectMapper mapper = new ObjectMapper();
    private final String liveApprovalId;

    public Cafe24ReviewCommentClient(Cafe24HttpClient http, String liveApprovalId) {
        this.http = http;
        this.liveApprovalId = liveApprovalId == null ? "" : liveApprovalId.strip();
    }

    /**
     * Everything the create request carries.
     *
     * @param shopNo    the observed shop; never defaulted here
     * @param boardNo   PATH only
     * @param articleNo PATH only — the review article the comment hangs under
     * @param content   the approved draft body, byte for byte
     * @param writer    {@code mall_id}
     * @param memberId  {@code mall_id}
     * @param password  the per-comment secret; the caller generated it and will not keep it
     */
    public record Comment(int shopNo, int boardNo, long articleNo, String content, String writer,
                          String memberId, String password) {
    }

    /** What the POST did. {@code commentNo} is null when the response did not name one. */
    public record Outcome(Kind kind, Long commentNo, Integer httpStatus) {

        public enum Kind { ACCEPTED, REJECTED, RETRYABLE, UNKNOWN }
    }

    /** Post the comment. Exactly one request; no retry on any outcome. */
    public Outcome post(String accessToken, String mallId, Comment comment) {
        URI uri = uri(mallId, comment.boardNo(), comment.articleNo());
        ensureLiveWriteAllowed(uri);
        String body = body(comment);
        assertContractShape(body);
        Cafe24HttpClient.Response response;
        try {
            response = http.postJson(uri, Map.of("Authorization", "Bearer " + accessToken), body);
        } catch (RuntimeException e) {
            return new Outcome(Outcome.Kind.UNKNOWN, null, null);
        }
        int status = response.statusCode();
        if (status == 200 || status == 201) {
            return new Outcome(Outcome.Kind.ACCEPTED, commentNo(response.body()), status);
        }
        if (status == 429) {
            return new Outcome(Outcome.Kind.RETRYABLE, null, status);
        }
        if (status >= 500) {
            return new Outcome(Outcome.Kind.UNKNOWN, null, status);
        }
        if (status == 401 || status == 403) {
            return new Outcome(Outcome.Kind.RETRYABLE, null, status);
        }
        // API diagnostics only — the error object's code/message, never the body we sent.
        log.warn("카페24 리뷰 댓글 등록 거부: status={} 사유={}", status, refusalReason(response.body()));
        return new Outcome(Outcome.Kind.REJECTED, null, status);
    }

    /**
     * The serialized body, read back and checked key by key before the one irreversible call.
     *
     * <p>The envelope is {@code {"shop_no", "request": {…}}} — SINGULAR, because the contract caps this
     * endpoint at one object per call (the article POST creates up to ten and takes {@code requests}).
     * That reading is recorded as {@code REQUEST_ENVELOPE_UNVERIFIED} in the execution doc until the
     * live proof confirms it; the check here exists so that if the live proof corrects the shape, the
     * correction lands in exactly one place and cannot regress.
     *
     * <p>Key names only; no value is compared, logged or carried into a message.
     */
    public void assertContractShape(String body) {
        JsonNode root;
        try {
            root = mapper.readTree(body);
        } catch (Exception e) {
            throw new IllegalStateException("카페24 댓글 요청을 검증할 수 없습니다.");
        }
        Set<String> top = new LinkedHashSet<>();
        root.fieldNames().forEachRemaining(top::add);
        if (!top.equals(Set.of("shop_no", "request"))) {
            throw new IllegalStateException("카페24 댓글 요청 봉투가 계약과 다릅니다.");
        }
        if (root.path("shop_no").asInt(0) <= 0) {
            throw new IllegalStateException("카페24 댓글 대상 상점 번호가 없습니다.");
        }
        Set<String> inner = new LinkedHashSet<>();
        root.path("request").fieldNames().forEachRemaining(inner::add);
        if (!inner.equals(Set.of("content", "writer", "member_id", "password", "secret"))) {
            throw new IllegalStateException("카페24 댓글 요청 필드 구성이 계약과 다릅니다.");
        }
    }

    /** The request body — only the five fields the adapter decided to send. */
    public String body(Comment c) {
        require(c.content(), "본문");
        require(c.writer(), "작성자");
        require(c.memberId(), "회원 식별자");
        require(c.password(), "댓글 비밀번호");
        if (c.password().length() < PASSWORD_MIN || c.password().length() > PASSWORD_MAX) {
            throw new IllegalStateException("카페24 댓글 비밀번호 길이가 계약 범위를 벗어납니다.");
        }
        if (c.writer().strip().length() > WRITER_MAX) {
            throw new IllegalStateException("카페24 댓글 작성자 값이 계약 상한을 넘습니다.");
        }
        if (c.articleNo() <= 0 || c.boardNo() <= 0) {
            throw new IllegalStateException("카페24 댓글 대상 글 번호가 올바르지 않습니다.");
        }
        if (c.shopNo() <= 0) {
            throw new IllegalStateException("카페24 댓글 대상 상점 번호가 없습니다.");
        }
        ObjectNode request = mapper.createObjectNode();
        request.put("content", c.content());
        request.put("writer", c.writer().strip());
        request.put("member_id", c.memberId().strip());
        request.put("password", c.password());
        // A shop's reply to a public review is public. The seller's review board is a public board;
        // hiding the reply would not hide the review.
        request.put("secret", "F");
        // `rating`, `parent_comment_no`, `input_channel`, `created_date`, `attach_file_urls` are
        // deliberately absent — see the class note and the execution doc's field table.
        ObjectNode root = mapper.createObjectNode();
        root.put("shop_no", c.shopNo());
        root.set("request", request);
        try {
            return mapper.writeValueAsString(root);
        } catch (Exception e) {
            throw new IllegalStateException("카페24 댓글 요청을 만들 수 없습니다.");
        }
    }

    private static void require(String value, String what) {
        if (value == null || value.isBlank()) {
            throw new IllegalStateException("카페24 댓글에 필요한 값이 없습니다: " + what);
        }
    }

    private String refusalReason(String body) {
        try {
            JsonNode error = mapper.readTree(body == null ? "" : body).path("error");
            String joined = (error.path("code").asText("") + " " + error.path("message").asText("")).strip();
            return joined.isEmpty() ? "(설명 없음)" : joined;
        } catch (Exception e) {
            return "(해석할 수 없는 응답)";
        }
    }

    /**
     * The created comment's number when the response names one. The create response's shape is not
     * documented by the vendored contract, so this parses opportunistically ({@code comment} object or
     * a one-element {@code comments} array) and a null is a normal answer — the adapter then finds the
     * comment by content hash on the read-back.
     */
    private Long commentNo(String responseBody) {
        if (responseBody == null || responseBody.isBlank()) {
            return null;
        }
        try {
            CreateEnvelope envelope = mapper.readValue(responseBody, CreateEnvelope.class);
            if (envelope.comment() != null && envelope.comment().commentNo() != null) {
                return envelope.comment().commentNo();
            }
            if (envelope.comments() != null && envelope.comments().size() == 1) {
                return envelope.comments().get(0).commentNo();
            }
            return null;
        } catch (Exception e) {
            return null;
        }
    }

    static URI uri(String mallId, int boardNo, long articleNo) {
        if (mallId == null || !MALL_ID_SHAPE.matcher(mallId).matches()) {
            throw new IllegalStateException("카페24 mall_id 형식이 올바르지 않습니다.");
        }
        if (boardNo <= 0 || articleNo <= 0) {
            throw new IllegalStateException("카페24 댓글 대상 형식이 올바르지 않습니다.");
        }
        return URI.create("https://" + mallId + ".cafe24api.com/api/v2/admin/boards/" + boardNo
                + "/articles/" + articleNo + "/comments");
    }

    /** Throws unless this write is either offline or covered by an armed approval id. */
    void ensureLiveWriteAllowed(URI uri) {
        String host = uri.getHost() == null ? "" : uri.getHost().toLowerCase(Locale.ROOT);
        boolean offline = LOOPBACK_HOSTS.contains(host) || host.endsWith(".localhost")
                || host.endsWith(".test") || host.endsWith(".local");
        if (offline) {
            return;
        }
        if (liveApprovalId.isEmpty()) {
            throw new Cafe24WriteApprovalRequired();
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    private record CreateEnvelope(@JsonProperty("comment") Created comment,
                                  @JsonProperty("comments") java.util.List<Created> comments) {
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    private record Created(@JsonProperty("comment_no") Long commentNo) {
    }
}
