"""Tests for manifest 1.3 provenance consistency.

The fix targets two regressions:
  1. The seller PDF is generated by a separate subprocess; the
     content engine writes the manifest unaware that the PDF
     exists. Result: `seller_report_ko_pdf.status="skipped"` even
     when the file is on disk.
  2. The manifest carries no scrape-side provenance (goodsNo,
     corpus_mode, sorts, review counts), making post-hoc audit
     impossible without re-deriving from raw artifacts.

`detect_seller_artifacts` reads the run dir and emits ok records
for any artifact found. `ManifestBuildContext.collection` carries
the new top-level provenance block.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from src.voc.content.manifest import (
    ArtifactRecord,
    ManifestBuildContext,
    build_phase_a_manifest,
    detect_seller_artifacts,
    skipped_record,
    validate_manifest,
)
from src.voc.content.paths import (
    SELLER_REPORT_SUBDIR,
    SHARED_SUBDIR,
)


@pytest.fixture
def fake_run_dir(tmp_path: Path) -> Path:
    run = tmp_path / "2026-05-01_product-test_run-001"
    (run / SELLER_REPORT_SUBDIR).mkdir(parents=True)
    (run / SHARED_SUBDIR).mkdir(parents=True)
    return run


@pytest.fixture
def fake_run_dir_with_pdf(fake_run_dir: Path) -> Path:
    pdf = fake_run_dir / SELLER_REPORT_SUBDIR / "seller_report_ko.pdf"
    pdf.write_bytes(b"%PDF-1.4 fake content for test\n")
    return fake_run_dir


def _minimal_ctx(run_dir: Path, *, collection: dict | None = None) -> ManifestBuildContext:
    # Touch an analysis report so analysis_report block has size.
    ar = run_dir / SHARED_SUBDIR / "analysis_report.json"
    ar.write_text(json.dumps({"schema_version": "3.0"}), encoding="utf-8")
    return ManifestBuildContext(
        run_dir=run_dir,
        product={"slug": "x", "name_ko": "테스트", "category": "테스트"},
        analysis_report_path=f"{SHARED_SUBDIR}/analysis_report.json",
        collection=collection or {},
    )


# -----------------------------------------------------------------------------
# detect_seller_artifacts: finds files on disk, returns ok records.
# -----------------------------------------------------------------------------


class TestDetectSellerArtifacts:
    def test_finds_seller_pdf(self, fake_run_dir_with_pdf: Path):
        detected = detect_seller_artifacts(fake_run_dir_with_pdf)
        assert "seller_report_ko_pdf" in detected
        rec = detected["seller_report_ko_pdf"]
        assert rec.status == "ok"
        assert rec.path == f"{SELLER_REPORT_SUBDIR}/seller_report_ko.pdf"
        assert rec.sha256 and len(rec.sha256) == 64
        assert rec.bytes and rec.bytes > 0

    def test_returns_empty_when_pdf_missing(self, fake_run_dir: Path):
        detected = detect_seller_artifacts(fake_run_dir)
        assert "seller_report_ko_pdf" not in detected

    def test_finds_interview_hooks_when_present(self, fake_run_dir: Path):
        hooks = fake_run_dir / SHARED_SUBDIR / "interview_hooks.json"
        hooks.write_text('{"hooks": []}', encoding="utf-8")
        detected = detect_seller_artifacts(fake_run_dir)
        assert "interview_hooks_json" in detected
        assert detected["interview_hooks_json"].status == "ok"


# -----------------------------------------------------------------------------
# Manifest reflects detected artifacts.
# -----------------------------------------------------------------------------


class TestManifestReflectsDetected:
    def test_manifest_marks_seller_pdf_ok_when_found(self, fake_run_dir_with_pdf: Path):
        detected = detect_seller_artifacts(fake_run_dir_with_pdf)
        ctx = _minimal_ctx(fake_run_dir_with_pdf)
        manifest = build_phase_a_manifest(
            ctx,
            seller_report_record=detected.get("seller_report_ko_pdf"),
        )
        assert manifest["artifacts"]["seller_report_ko_pdf"]["status"] == "ok"
        assert manifest["artifacts"]["seller_report_ko_pdf"]["path"]

    def test_manifest_validates_when_pdf_present_and_recorded(
        self, fake_run_dir_with_pdf: Path,
    ):
        detected = detect_seller_artifacts(fake_run_dir_with_pdf)
        ctx = _minimal_ctx(fake_run_dir_with_pdf)
        manifest = build_phase_a_manifest(
            ctx,
            seller_report_record=detected.get("seller_report_ko_pdf"),
        )
        # validate_manifest should not raise.
        validate_manifest(manifest, fake_run_dir_with_pdf)

    def test_manifest_falls_back_to_skipped_when_pdf_missing(
        self, fake_run_dir: Path,
    ):
        detected = detect_seller_artifacts(fake_run_dir)
        ctx = _minimal_ctx(fake_run_dir)
        manifest = build_phase_a_manifest(
            ctx,
            seller_report_record=detected.get("seller_report_ko_pdf"),
        )
        # No detected record → default skipped.
        assert manifest["artifacts"]["seller_report_ko_pdf"]["status"] == "skipped"


# -----------------------------------------------------------------------------
# Collection provenance block.
# -----------------------------------------------------------------------------


class TestCollectionProvenance:
    def test_collection_block_omitted_when_empty(self, fake_run_dir: Path):
        ctx = _minimal_ctx(fake_run_dir)
        manifest = build_phase_a_manifest(ctx)
        # Empty dict is dropped to keep legacy manifests byte-identical.
        assert "collection" not in manifest

    def test_collection_block_carries_required_fields(self, fake_run_dir: Path):
        ctx = _minimal_ctx(
            fake_run_dir,
            collection={
                "product_url": "https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000171427",
                "goodsNo": "A000000171427",
                "corpus_mode": "observable_multi_sort",
                "sorts_attempted": ["DATETIME_DESC", "RATING_ASC", "RATING_DESC"],
                "sorts_succeeded": ["DATETIME_DESC", "RATING_ASC"],
                "partial_success": True,
                "review_count_collected": 2143,
                "review_count_analyzed": 2029,
                "primary_sort": "DATETIME_DESC",
            },
        )
        manifest = build_phase_a_manifest(ctx)
        assert "collection" in manifest
        col = manifest["collection"]
        for key in (
            "product_url", "goodsNo", "corpus_mode",
            "sorts_attempted", "sorts_succeeded", "partial_success",
            "review_count_collected", "review_count_analyzed",
            "primary_sort",
        ):
            assert key in col, f"collection missing {key}"
        assert col["partial_success"] is True
        assert col["review_count_analyzed"] == 2029

    def test_collection_does_not_break_validate(self, fake_run_dir: Path):
        ctx = _minimal_ctx(
            fake_run_dir,
            collection={"goodsNo": "A123", "corpus_mode": "primary_only"},
        )
        manifest = build_phase_a_manifest(ctx)
        # validate_manifest is silent on the new key (additive contract).
        validate_manifest(manifest, fake_run_dir)
