/**
 * CONTROLLED DIAGNOSTIC SAVE of an already-fired review download — save → validate → delete.
 *
 * After the supervised approved-index confirm click fires a real download (see
 * `review-usage-confirm.ts`), this module saves it to a gitignored quarantine path, validates it is
 * structurally a real `.xlsx`, and then DELETES it. It is strictly diagnostic:
 *
 *   - It is the ONLY module that calls `download.saveAs(...)` outside `runExport`, and the only one
 *     in the confirm chain that touches `node:fs`. Both the CLI and `review-usage-confirm.ts`
 *     source-guard `saveAs` to ABSENT, so the file write is confined here.
 *   - It NEVER writes status, sets LAST_SUCCESS, or names the backend client. No xlsx parser is used —
 *     validation is a bounded magic-byte sniff (ZIP local-header + OOXML marker), so NO cell is ever
 *     read and `rawCellLeak` is structurally false. An OPTIONAL injected `uploadFn` (the
 *     `--diagnose-upload-saved-review-download` path) may upload the validated file to the backend
 *     BEFORE it is deleted — the fn owns the only backend call; this module never names it and
 *     surfaces only the fn's sanitized `UploadInspection`.
 *   - The saved file is DELETED after validation (`delete-after-validate`), so no real review data
 *     lingers on disk. The destination basename is generated by our code (a salted hash of the raw
 *     name), never the raw NAVER filename, and the raw name/path are never returned or logged.
 *   - All output is sanitized — enums / booleans / coarse buckets / a salted 16-hex hash.
 *
 * The filesystem ops are injectable (`DownloadSaveIo`) so the save/validate/delete cycle is
 * hermetically testable with an in-memory fake; the default `io` is backed by `node:fs`.
 */
import { closeSync, mkdirSync, openSync, readSync, statSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { messageFingerprint } from "./export-click-signals";
import { extensionCategory, type ExtensionCategory } from "./review-export";
import type { UploadInspection } from "./review-upload-diagnostic";

/** Fixed category for the quarantine location — never the raw path. */
const PATH_CATEGORY = "downloads_diagnostic_quarantine" as const;

/** How many leading bytes to read for the structural (magic-byte) sniff. */
const DEFAULT_HEAD_BYTES = 64 * 1024;

/** Minimal structural surface of a download we save from (matches `ConfirmDownload`). */
export interface SaveableDownload {
  suggestedFilename(): string;
  saveAs(path: string): Promise<void>;
}

/** Injectable filesystem ops — default is `node:fs`-backed; tests pass an in-memory fake. */
export interface DownloadSaveIo {
  ensureDir(dir: string): void;
  fileSize(path: string): number;
  readHead(path: string, maxBytes: number): Uint8Array;
  removeFile(path: string): void;
}

/** Coarse file-size bucket — never the exact byte count. */
export type FileSizeBucket = "empty" | "tiny" | "small" | "medium" | "large";

/** Sanitized inspection of a saved-then-deleted diagnostic download. Every leaf is non-sensitive. */
export interface SavedDownloadInspection {
  downloadSaved: boolean;
  savedPathCategory: typeof PATH_CATEGORY;
  savedBasenameHash: string;
  savedExtensionCategory: ExtensionCategory;
  fileSizeBucket: FileSizeBucket;
  xlsxReadable: boolean;
  /** Sheet/row/column/header validation is deferred to a follow-up PR that adds a parser. */
  workbookContentValidation: "deferred";
  /** No cell is ever read (no parser) — structurally true. */
  rawCellLeak: false;
  fileRetained: false;
  retentionPolicy: "delete-after-validate";
  /**
   * Present ONLY when an `uploadFn` was injected (the `--diagnose-upload-saved-review-download`
   * path) AND the file validated as a real `.xlsx`. A sanitized backend ingest inspection — its
   * presence means the backend DB was ingested (a real, higher-consequence state change). Absent
   * on the observe/save-only paths.
   */
  uploaded?: UploadInspection;
}

/** Exact top-level key allow-list — used by the offline no-leak test. */
export const SAVED_DOWNLOAD_INSPECTION_KEYS: ReadonlyArray<keyof SavedDownloadInspection> = [
  "downloadSaved",
  "savedPathCategory",
  "savedBasenameHash",
  "savedExtensionCategory",
  "fileSizeBucket",
  "xlsxReadable",
  "workbookContentValidation",
  "rawCellLeak",
  "fileRetained",
  "retentionPolicy",
  "uploaded",
];

export interface SaveDownloadOpts {
  /** The gitignored quarantine directory (e.g. `downloads/diagnostic`). */
  dir: string;
  /** Salt for the basename hash (shared `storageProbeSalt`). */
  salt?: string;
  /** Injected filesystem ops; default is `node:fs`. */
  io?: DownloadSaveIo;
  /** Override for the structural-sniff head size (test convenience). */
  headBytes?: number;
  /**
   * Optional CONTROLLED-UPLOAD hook (the `--diagnose-upload-saved-review-download` path). When set
   * AND the saved file validates as a real `.xlsx`, the quarantine file is uploaded to the backend
   * by the injected fn BEFORE it is deleted (upload-before-delete). The fn owns the only backend
   * call and returns a sanitized `UploadInspection`. This module never names `uploadReviewFile`,
   * never writes status, and never lets the raw path escape — the fn receives it transiently.
   */
  uploadFn?: (path: string) => Promise<UploadInspection>;
}

/** Pure: coarse size bucket (never the exact count). */
export function fileSizeBucket(bytes: number): FileSizeBucket {
  if (bytes <= 0) return "empty";
  if (bytes <= 1024) return "tiny";
  if (bytes <= 100 * 1024) return "small";
  if (bytes <= 2 * 1024 * 1024) return "medium";
  return "large";
}

/**
 * Pure: the generated quarantine basename — a salted hash of the RAW name plus the derived extension
 * category. The raw NAVER filename is never embedded.
 */
export function diagnosticBasenameFor(
  salt: string | undefined,
  rawFilename: string,
  category: ExtensionCategory,
): string {
  const ext = category === "unknown" ? "bin" : category;
  return `review-diagnostic-${messageFingerprint(salt, rawFilename)}.${ext}`;
}

/**
 * Pure: is the head of the file structurally a real OOXML/xlsx zip? Requires the ZIP local-header
 * magic (`50 4B 03 04`) AND the OOXML content-types entry name near the start. Reads NO cell — only
 * the structural shape — so it can never echo content.
 */
export function sniffXlsxReadable(head: Uint8Array): boolean {
  if (head.length < 4) return false;
  const hasZipMagic = head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04;
  if (!hasZipMagic) return false;
  let s = "";
  for (let i = 0; i < head.length; i += 1) s += String.fromCharCode(head[i] ?? 0);
  return s.includes("[Content_Types].xml");
}

/** The real `node:fs`-backed io used when none is injected. */
const defaultIo: DownloadSaveIo = {
  ensureDir(dir: string): void {
    mkdirSync(dir, { recursive: true });
  },
  fileSize(path: string): number {
    return statSync(path).size;
  },
  readHead(path: string, maxBytes: number): Uint8Array {
    const fd = openSync(path, "r");
    try {
      const buf = Buffer.alloc(maxBytes);
      const read = readSync(fd, buf, 0, maxBytes, 0);
      return buf.subarray(0, read);
    } finally {
      closeSync(fd);
    }
  },
  removeFile(path: string): void {
    unlinkSync(path);
  },
};

function failedInspection(salt: string | undefined, basename: string, category: ExtensionCategory): SavedDownloadInspection {
  return {
    downloadSaved: false,
    savedPathCategory: PATH_CATEGORY,
    savedBasenameHash: basename ? messageFingerprint(salt, basename) : "",
    savedExtensionCategory: category,
    fileSizeBucket: "empty",
    xlsxReadable: false,
    workbookContentValidation: "deferred",
    rawCellLeak: false,
    fileRetained: false,
    retentionPolicy: "delete-after-validate",
  };
}

/**
 * Save an already-fired download to the quarantine dir, validate it structurally, then DELETE it.
 * Returns a sanitized inspection. Never throws — a save/validate failure degrades to a sanitized
 * `downloadSaved:false` record. The file is always removed in `finally` (delete-after-validate).
 */
export async function saveAndInspectDownload(
  download: SaveableDownload,
  opts: SaveDownloadOpts,
): Promise<SavedDownloadInspection> {
  const io = opts.io ?? defaultIo;
  const headBytes = opts.headBytes ?? DEFAULT_HEAD_BYTES;
  let targetPath = "";
  let basename = "";
  let category: ExtensionCategory = "unknown";
  try {
    const rawName = download.suggestedFilename();
    category = extensionCategory(rawName);
    basename = diagnosticBasenameFor(opts.salt, rawName, category);
    targetPath = join(opts.dir, basename);
    io.ensureDir(opts.dir);
    await download.saveAs(targetPath);
    const size = io.fileSize(targetPath);
    const head = io.readHead(targetPath, headBytes);
    const xlsxReadable = sniffXlsxReadable(head);
    // Controlled backend upload (only when the hook is wired AND the file is a real .xlsx): upload
    // the quarantine file BEFORE the finally-block deletes it. A non-OOXML payload is never uploaded.
    // The injected fn owns the sole backend call and returns a sanitized inspection (never throws
    // past its own boundary, but guard here too so a hook error still degrades cleanly).
    const uploaded = opts.uploadFn && xlsxReadable ? await opts.uploadFn(targetPath) : undefined;
    return {
      downloadSaved: true,
      savedPathCategory: PATH_CATEGORY,
      savedBasenameHash: messageFingerprint(opts.salt, basename),
      savedExtensionCategory: category,
      fileSizeBucket: fileSizeBucket(size),
      xlsxReadable,
      workbookContentValidation: "deferred",
      rawCellLeak: false,
      fileRetained: false,
      retentionPolicy: "delete-after-validate",
      ...(uploaded ? { uploaded } : {}),
    };
  } catch {
    return failedInspection(opts.salt, basename, category);
  } finally {
    // delete-after-validate: best-effort cleanup so no real review data ever lingers on disk.
    if (targetPath) {
      try {
        io.removeFile(targetPath);
      } catch {
        /* best-effort — the quarantine dir is gitignored and cleared on the next run anyway */
      }
    }
  }
}
