/**
 * CONTROLLED DIAGNOSTIC SAVE of an already-fired review download — save → validate → delete.
 *
 * After the supervised approved-index confirm click fires a real download (see
 * `review-usage-confirm.ts`), this module saves it to a gitignored quarantine path, validates it is
 * structurally a real `.xlsx`, and then DELETES it. It is strictly diagnostic:
 *
 *   - It is the ONLY module that calls `download.saveAs(...)` outside `runExport`, and the only one
 *     in the confirm chain that touches `node:fs`. Both the CLI and `review-usage-confirm.ts`
 *     source-guard `saveAs` to ABSENT, so the file write is confined here.
 *   - It NEVER writes status, sets LAST_SUCCESS, or names the backend client. No xlsx parser is used —
 *     validation is a bounded magic-byte sniff (ZIP local-header + OOXML marker), so NO cell is ever
 *     read and `rawCellLeak` is structurally false. An OPTIONAL injected `uploadFn` (the
 *     `--diagnose-upload-saved-review-download` path) may upload the validated file to the backend
 *     BEFORE it is deleted — the fn owns the only backend call; this module never names it and
 *     surfaces only the fn's sanitized `UploadInspection`.
 *   - The saved file is DELETED after validation (`delete-after-validate`), so no real review data
 *     lingers on disk. The destination basename is generated by our code (a salted hash of the raw
 *     name), never the raw NAVER filename, and the raw name/path are never returned or logged.
 *   - All output is sanitized — enums / booleans / coarse buckets / a salted 16-hex hash.
 *
 * The filesystem ops are injectable (`DownloadSaveIo`) so the save/validate/delete cycle is
 * hermetically testable with an in-memory fake; the default `io` is backed by `node:fs`.
 */
import { closeSync, mkdirSync, openSync, readSync, statSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { TextDecoder } from "node:util";
import { messageFingerprint } from "./export-click-signals";
import { extensionCategory, type ExtensionCategory } from "./review-export";
import type { UploadInspection } from "./review-upload-diagnostic";

/** Fixed category for the quarantine location — never the raw path. */
const PATH_CATEGORY = "downloads_diagnostic_quarantine" as const;

/** How many leading bytes to read for the structural (magic-byte) sniff. */
const DEFAULT_HEAD_BYTES = 64 * 1024;

/** Minimal structural surface of a download we save from (matches `ConfirmDownload`). */
export interface SaveableDownload {
  suggestedFilename(): string;
  saveAs(path: string): Promise<void>;
}

/** Injectable filesystem ops — default is `node:fs`-backed; tests pass an in-memory fake. */
export interface DownloadSaveIo {
  ensureDir(dir: string): void;
  fileSize(path: string): number;
  readHead(path: string, maxBytes: number): Uint8Array;
  removeFile(path: string): void;
}

/** Coarse file-size bucket — never the exact byte count. */
export type FileSizeBucket = "empty" | "tiny" | "small" | "medium" | "large";

/**
 * Sanitized inspection of a saved-then-deleted diagnostic download. Every leaf is non-sensitive.
 * `R` is the (sanitized) result type of an optional pre-delete `inspectFn` — `never` by default,
 * so observe/save-only callers are unaffected.
 */
export interface SavedDownloadInspection<R = never> {
  downloadSaved: boolean;
  savedPathCategory: typeof PATH_CATEGORY;
  savedBasenameHash: string;
  savedExtensionCategory: ExtensionCategory;
  fileSizeBucket: FileSizeBucket;
  xlsxReadable: boolean;
  /**
   * Positive byte-derived structural family (enum only). Meaningful only when `downloadSaved` is true;
   * on the degraded/no-save path it defaults to `"empty"`. Never carries content.
   */
  fileFamily: FileFamily;
  /** Sheet/row/column/header validation is deferred to a follow-up PR that adds a parser. */
  workbookContentValidation: "deferred";
  /** No cell is ever read by THIS module (no parser) — structurally true. */
  rawCellLeak: false;
  fileRetained: false;
  retentionPolicy: "delete-after-validate";
  /** True when delete-after-validate could NOT remove the file — observable, never silently retained. */
  deleteFailed: boolean;
  /**
   * Present ONLY when an `uploadFn` was injected (the `--diagnose-upload-saved-review-download`
   * path) AND the file validated as a real `.xlsx`. A sanitized backend ingest inspection — its
   * presence means the backend DB was ingested (a real, higher-consequence state change). Absent
   * on the observe/save-only paths.
   */
  uploaded?: UploadInspection;
  /**
   * Present ONLY when an `inspectFn` was injected AND the file validated as a real `.xlsx`. The
   * injected fn runs on the still-present quarantine file BEFORE the delete and returns a SANITISED
   * inspection (e.g. the Gate-4 schema-shape). This module stays parser-free and decoupled — it
   * never reads a cell itself and never imports the inspector's module.
   */
  inspection?: R;
}

/** Exact top-level key allow-list — used by the offline no-leak test. */
export const SAVED_DOWNLOAD_INSPECTION_KEYS: ReadonlyArray<keyof SavedDownloadInspection<unknown>> = [
  "downloadSaved",
  "savedPathCategory",
  "savedBasenameHash",
  "savedExtensionCategory",
  "fileSizeBucket",
  "xlsxReadable",
  "fileFamily",
  "workbookContentValidation",
  "rawCellLeak",
  "fileRetained",
  "retentionPolicy",
  "deleteFailed",
  "uploaded",
  "inspection",
];

export interface SaveDownloadOpts<R = never> {
  /** The gitignored quarantine directory (e.g. `downloads/diagnostic`). */
  dir: string;
  /** Salt for the basename hash (shared `storageProbeSalt`). */
  salt?: string;
  /** Injected filesystem ops; default is `node:fs`. */
  io?: DownloadSaveIo;
  /** Override for the structural-sniff head size (test convenience). */
  headBytes?: number;
  /**
   * Optional CONTROLLED-UPLOAD hook (the `--diagnose-upload-saved-review-download` path). When set
   * AND the saved file validates as a real `.xlsx`, the quarantine file is uploaded to the backend
   * by the injected fn BEFORE it is deleted (upload-before-delete). The fn owns the only backend
   * call and returns a sanitized `UploadInspection`. This module never names `uploadReviewFile`,
   * never writes status, and never lets the raw path escape — the fn receives it transiently.
   */
  uploadFn?: (path: string) => Promise<UploadInspection>;
  /**
   * Optional pre-delete INSPECT hook (the Gate-4 `--inspect-schema-shape` path). When set AND the
   * saved file validates as a real `.xlsx`, the injected fn reads the still-present quarantine file
   * BEFORE the delete and returns a SANITISED result (e.g. the schema-shape). The fn owns whatever
   * read it performs; this module remains parser-free and never imports the inspector. The raw path
   * is passed transiently and never logged or returned.
   */
  inspectFn?: (path: string) => Promise<R>;
}

/** Pure: coarse size bucket (never the exact count). */
export function fileSizeBucket(bytes: number): FileSizeBucket {
  if (bytes <= 0) return "empty";
  if (bytes <= 1024) return "tiny";
  if (bytes <= 100 * 1024) return "small";
  if (bytes <= 2 * 1024 * 1024) return "medium";
  return "large";
}

/**
 * Pure: the generated quarantine basename — a salted hash of the RAW name plus the derived extension
 * category. The raw NAVER filename is never embedded.
 */
export function diagnosticBasenameFor(
  salt: string | undefined,
  rawFilename: string,
  category: ExtensionCategory,
): string {
  const ext = category === "unknown" ? "bin" : category;
  return `review-diagnostic-${messageFingerprint(salt, rawFilename)}.${ext}`;
}

/**
 * Pure: is the head of the file structurally a real OOXML/xlsx zip? Requires the ZIP local-header
 * magic (`50 4B 03 04`) AND the OOXML content-types entry name near the start. Reads NO cell — only
 * the structural shape — so it can never echo content.
 */
export function sniffXlsxReadable(head: Uint8Array): boolean {
  if (head.length < 4) return false;
  const hasZipMagic = head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04;
  if (!hasZipMagic) return false;
  let s = "";
  for (let i = 0; i < head.length; i += 1) s += String.fromCharCode(head[i] ?? 0);
  return s.includes("[Content_Types].xml");
}

/**
 * Byte-derived POSITIVE family of a saved artifact — a sanitized structural verdict so an
 * `ARTIFACT_INVALID` cause can be told apart (HTML interstitial vs CSV/text export vs truncated vs
 * non-OOXML zip vs empty) without ever exposing content. Enum only.
 */
export type FileFamily =
  | "empty"
  | "too_small_or_partial"
  | "ooxml_zip_like"
  | "zip_non_ooxml_or_partial"
  | "html_like"
  | "csv_like"
  | "binary_unknown";

/** Below this, a payload is too small to be any plausible export — treated as truncated/incomplete. */
const MIN_PLAUSIBLE_BYTES = 8;

/** Pure: does the head begin with the ZIP local-header magic (`50 4B 03 04`)? */
function hasZipLocalHeaderMagic(head: Uint8Array): boolean {
  return head.length >= 4 && head[0] === 0x50 && head[1] === 0x4b && head[2] === 0x03 && head[3] === 0x04;
}

/**
 * Pure, CONSERVATIVE text check. True only for clean printable ASCII / valid UTF-8 (CSV/TSV/plain text) —
 * never for control-heavy or binary payloads. Rejects any C0 control other than tab/LF/CR, plus NUL and
 * DEL; then requires a STRICT (fatal) UTF-8 decode, tolerating a multibyte char cut at the head boundary
 * (retry with up to 3 trailing bytes trimmed). Arbitrary `>=0x80` bytes are NOT assumed to be text — only
 * genuinely-valid UTF-8 passes. Reads bytes for the verdict; returns a boolean, never any content.
 */
function looksLikeText(head: Uint8Array): boolean {
  if (head.length === 0) return false;
  for (let i = 0; i < head.length; i += 1) {
    const b = head[i] ?? 0;
    const allowedControl = b === 0x09 || b === 0x0a || b === 0x0d;
    if ((b < 0x20 && !allowedControl) || b === 0x7f) return false;
  }
  for (let trim = 0; trim <= 3; trim += 1) {
    const slice = trim === 0 ? head : head.subarray(0, head.length - trim);
    if (slice.length === 0) break;
    try {
      new TextDecoder("utf-8", { fatal: true }).decode(slice);
      return true;
    } catch {
      // possibly a multibyte sequence cut at the head boundary — trim one more trailing byte and retry
    }
  }
  return false;
}

/**
 * Pure: classify a saved artifact into a POSITIVE, sanitized byte-family. Reads only the already-in-memory
 * head bytes + the coarse size; returns an ENUM only — never any content. Precedence (first match wins):
 * empty → too-small → ooxml → zip-without-proven-ooxml → markup → strict-text → binary.
 */
export function classifyFileFamily(head: Uint8Array, size: number): FileFamily {
  if (size <= 0 || head.length === 0) return "empty";
  if (size < MIN_PLAUSIBLE_BYTES) return "too_small_or_partial";
  if (sniffXlsxReadable(head)) return "ooxml_zip_like";
  if (hasZipLocalHeaderMagic(head)) return "zip_non_ooxml_or_partial";
  let i = 0;
  while (i < head.length && (head[i] === 0x20 || head[i] === 0x09 || head[i] === 0x0a || head[i] === 0x0d)) {
    i += 1;
  }
  if (i < head.length && head[i] === 0x3c) return "html_like";
  if (looksLikeText(head)) return "csv_like";
  return "binary_unknown";
}

/** The real `node:fs`-backed io used when none is injected. */
const defaultIo: DownloadSaveIo = {
  ensureDir(dir: string): void {
    mkdirSync(dir, { recursive: true });
  },
  fileSize(path: string): number {
    return statSync(path).size;
  },
  readHead(path: string, maxBytes: number): Uint8Array {
    const fd = openSync(path, "r");
    try {
      const buf = Buffer.alloc(maxBytes);
      const read = readSync(fd, buf, 0, maxBytes, 0);
      return buf.subarray(0, read);
    } finally {
      closeSync(fd);
    }
  },
  removeFile(path: string): void {
    unlinkSync(path);
  },
};

function failedInspection<R = never>(
  salt: string | undefined,
  basename: string,
  category: ExtensionCategory,
): SavedDownloadInspection<R> {
  return {
    downloadSaved: false,
    savedPathCategory: PATH_CATEGORY,
    savedBasenameHash: basename ? messageFingerprint(salt, basename) : "",
    savedExtensionCategory: category,
    fileSizeBucket: "empty",
    xlsxReadable: false,
    fileFamily: "empty",
    workbookContentValidation: "deferred",
    rawCellLeak: false,
    fileRetained: false,
    retentionPolicy: "delete-after-validate",
    deleteFailed: false,
  };
}

/**
 * Save an already-fired download to the quarantine dir, validate it structurally, then DELETE it.
 * Returns a sanitized inspection. Never throws — a save/validate failure degrades to a sanitized
 * `downloadSaved:false` record. The file is always removed in `finally` (delete-after-validate).
 */
export async function saveAndInspectDownload<R = never>(
  download: SaveableDownload,
  opts: SaveDownloadOpts<R>,
): Promise<SavedDownloadInspection<R>> {
  const io = opts.io ?? defaultIo;
  const headBytes = opts.headBytes ?? DEFAULT_HEAD_BYTES;
  let targetPath = "";
  let basename = "";
  let category: ExtensionCategory = "unknown";
  // `result` is the reference returned from try/catch; the finally block mutates `deleteFailed` on
  // it AFTER the delete attempt, so the caller sees an HONEST cleanup outcome.
  let result: SavedDownloadInspection<R> = failedInspection<R>(opts.salt, basename, category);
  try {
    const rawName = download.suggestedFilename();
    category = extensionCategory(rawName);
    basename = diagnosticBasenameFor(opts.salt, rawName, category);
    targetPath = join(opts.dir, basename);
    io.ensureDir(opts.dir);
    await download.saveAs(targetPath);
    const size = io.fileSize(targetPath);
    const head = io.readHead(targetPath, headBytes);
    const xlsxReadable = sniffXlsxReadable(head);
    const fileFamily = classifyFileFamily(head, size);
    // Pre-delete hooks run ONLY when the file is a structurally-valid .xlsx, and BEFORE the finally
    // delete. A non-OOXML payload is never uploaded or inspected. Each injected fn owns its own
    // read/call and returns a sanitized result; this module never parses a cell itself.
    const uploaded = opts.uploadFn && xlsxReadable ? await opts.uploadFn(targetPath) : undefined;
    const inspection = opts.inspectFn && xlsxReadable ? await opts.inspectFn(targetPath) : undefined;
    result = {
      downloadSaved: true,
      savedPathCategory: PATH_CATEGORY,
      savedBasenameHash: messageFingerprint(opts.salt, basename),
      savedExtensionCategory: category,
      fileSizeBucket: fileSizeBucket(size),
      xlsxReadable,
      fileFamily,
      workbookContentValidation: "deferred",
      rawCellLeak: false,
      fileRetained: false,
      retentionPolicy: "delete-after-validate",
      deleteFailed: false,
      ...(uploaded ? { uploaded } : {}),
      ...(inspection !== undefined ? { inspection } : {}),
    };
    return result;
  } catch {
    result = failedInspection<R>(opts.salt, basename, category);
    return result;
  } finally {
    // delete-after-validate: best-effort cleanup so no real review data ever lingers on disk. Record
    // an honest `deleteFailed` rather than silently assuming the unlink succeeded.
    if (targetPath) {
      try {
        io.removeFile(targetPath);
        result.deleteFailed = false;
      } catch {
        result.deleteFailed = true;
      }
    }
  }
}
