package com.sellerops.connector.cafe24.spike;

import java.util.List;

/**
 * The single, fakeable network boundary of the reply spike — mirroring the
 * discipline of the production {@link com.sellerops.connector.cafe24.Cafe24HttpClient}
 * but kept <b>separate</b> so the production interface (form-POST + GET only) is not
 * widened to carry a comment-write method. Unit tests substitute a fake, so no spike
 * test can reach the network by construction.
 *
 * <p>Only three operations exist — observe one article, list its comments, create one
 * comment — and there is deliberately no update/delete method: the spike never PUTs
 * {@code reply_status} and never deletes a comment.
 */
public interface SpikeReplyTransport {

    /**
     * Read one article's current reply state (GET a single board article).
     *
     * @throws SpikeTransportException on any network / non-200 / unexpected shape
     */
    ArticleObservation observeArticle(String mallId, String accessToken, int boardNo, long articleNo);

    /**
     * List the comments on one article (GET comments), returning only the fields the
     * spike needs: the comment number and the writer (for own-marker detection).
     *
     * @throws SpikeTransportException on any network / non-200 / unexpected shape
     */
    List<CommentObservation> listComments(String mallId, String accessToken, int boardNo, long articleNo);

    /**
     * Create exactly one comment (POST). Implementations must send the version-pinned
     * admin call and parse the created comment defensively.
     *
     * @throws SpikeCommentRejectedException on a 4xx / field-mismatch rejection
     *     (a capability signal → verdict C)
     * @throws SpikeTransportException on a network / 5xx / unexpected-shape failure
     *     (a HALT, not a rejection)
     */
    CommentObservation createComment(String mallId, String accessToken, int boardNo, long articleNo,
                                     CommentDraft draft);

    /** One article's observable reply state — no title, body, writer, or PII. */
    record ArticleObservation(long articleNo, int boardNo, String rawReplyStatus) {
    }

    /**
     * One comment as the spike sees it. {@code writer} is used ONLY to detect the
     * spike's own prior comment (equality against the fixed marker) and is never
     * placed in a result, log, or proof.
     */
    record CommentObservation(long commentNo, String writer) {
    }

    /**
     * The comment to create. {@code password} is a {@code char[]} generated by
     * {@link java.security.SecureRandom}, held only in memory, and must never be
     * logged, returned, or serialized by any implementation.
     */
    record CommentDraft(String content, String writer, char[] password) {

        /** Masked — the draft carries the memory-only password. */
        @Override
        public String toString() {
            return "CommentDraft[content=<masked>, writer=<masked>, password=<masked>]";
        }
    }
}
