-- Opportunity Engine v1 — the seller's DECISION about one improvement opportunity, and the draft that
-- decision prepared.
--
-- An opportunity itself is not stored. It is DERIVED, on every read, from a review issue the extractor
-- already holds (its aspect × problem, its evidence count, its dominant product) and from whether the
-- seller's own knowledge mentions that aspect — the same rule every time, over rows that already exist,
-- so this table can never say an opportunity exists that the evidence no longer supports. What the
-- evidence cannot know is what the seller decided about it, and that is the only thing kept here.
--
-- A row exists ONLY once the seller accepted or dismissed. No row = open, and an opportunity whose
-- issue is later dismissed, resolved, or falls under the repeat threshold simply stops being derived;
-- its row stays inert (an annotation over operational truth, never a competing authority over it —
-- the proactive_case rule, applied again).
--
-- Deliberately NOT here: a cause, an expected effect, a priority score, a product/channel override, a
-- workflow state machine. The draft is a scaffold composed from facts and the seller's own passages;
-- nothing in it is generated by a model, and nothing here can publish it anywhere.
create table improvement_opportunity (
    id           uuid        primary key,
    org_id       uuid        not null references organizations (id),
    issue_id     uuid        not null references review_issues (id),

    -- One of OpportunityKind. Closed in code, like every other text-stored vocabulary in this schema.
    kind         text        not null,
    -- ACCEPTED (a draft was prepared) or DISMISSED. OPEN is the absence of a row.
    status       text        not null,

    -- The prepared draft, seller-editable. Present only while ACCEPTED.
    draft_title  text,
    draft_body   text,

    decided_at   timestamptz not null,
    created_at   timestamptz not null,
    updated_at   timestamptz not null
);

-- "One decision per opportunity" — identity is (issue, kind), a property of the table.
create unique index uq_improvement_opportunity_identity
    on improvement_opportunity (org_id, issue_id, kind);

create index ix_improvement_opportunity_org_issue
    on improvement_opportunity (org_id, issue_id);

comment on table improvement_opportunity is
    'Seller decision (accept/dismiss) and prepared draft for one derived improvement opportunity (Opportunity Engine v1). No row = open.';
