import { useState } from "react";
import { Btn } from "../ui/Btn";
import { KnowledgeQuickAdd } from "../knowledge/KnowledgeQuickAdd";
import { api } from "../../lib/apiClient";
import type { KnowledgeTopicValue } from "../../lib/knowledgeWords";
import type { KnowledgeSourceType, OrgKnowledgeType } from "../../lib/types";

export { titleFor } from "../knowledge/KnowledgeQuickAdd";

/**
 * 답변 기준 추가 — write the missing knowledge without leaving the inquiry or the review.
 *
 * <b>The seller already told us everything except the sentence.</b> The product, the channel and the
 * question are on screen; sending them to the library to search for the product again would make
 * them re-establish context the machine has. So this opens the ONE structured editor
 * ({@link KnowledgeQuickAdd}) with the scope fixed by what was missing.
 *
 * <b>ORG is not a link any more.</b> A company-wide gap used to say 「운영 정책에 추가하기」 and send
 * the seller to a settings screen, where they wrote a title and a body and then came back and
 * regenerated by hand — the one gap the product could name and the one it made the seller walk for.
 * The two scopes now save through their own endpoints and return here the same way.
 *
 * <b>It saves and re-asks. It does not send.</b> Saving re-indexes, the caller regenerates, and the
 * regenerated draft goes through the same approval and the same confirm-before-send as every other
 * one. Nothing here reaches a marketplace.
 *
 * <b>Answering an ask closes THAT ask</b> (Knowledge Gap Continuity v1). When the gap was filed in
 * 확인 필요, the row's id came back with it, and the save routes through `accept` — the one write
 * that files the fact AND closes the exact row, in one transaction, recording which source it
 * became. Before this the seller answered a gap here and met the identical ask again in the inbox.
 *
 * <b>By identity, never by resemblance.</b> No other ask is closed, and knowledge written anywhere
 * else — the library, the settings screen — closes nothing: deciding that a sentence a seller just
 * wrote answers an ask that was phrased differently is exactly the guess this product does not make.
 * With no `candidateId` this writes an ordinary source and leaves every card standing.
 */
export function AnswerBasisQuickAdd({
  scope = "PRODUCT",
  productId,
  productName,
  topic,
  candidateId,
  onSaved,
}: {
  /** Which corpus was missing the answer. PRODUCT needs a `productId`. */
  scope?: "PRODUCT" | "ORG";
  productId?: string | null;
  productName?: string | null;
  /** The operating topic the question named, when the retrieval named one. */
  topic?: KnowledgeTopicValue | null;
  /**
   * The 확인 필요 row this ask was filed as, when it was filed.
   *
   * Present ⇒ saving closes exactly that row and records the source it became. Absent ⇒ an ordinary
   * source is written and no card is touched.
   */
  candidateId?: string | null;
  onSaved: () => void | Promise<void>;
}) {
  const [open, setOpen] = useState(false);

  if (!open) {
    return (
      <div className="mt-3">
        <Btn onClick={() => setOpen(true)}>답변 기준 추가</Btn>
      </div>
    );
  }

  return (
    <KnowledgeQuickAdd
      scope={scope}
      productId={productId}
      productName={productName}
      topic={topic}
      saveLabel="저장하고 다시 답변 만들기"
      onSave={async (value) => {
        if (candidateId) {
          // One write: the fact is filed and the ask that prompted it is closed, together. A partial
          // failure cannot leave a fact stored under an ask that is still asking for it.
          await api.acceptKnowledgeCandidate(candidateId, {
            title: value.title,
            content: value.body,
            variantId: value.variantId,
            ...(scope === "PRODUCT"
              ? { sourceType: value.topic as KnowledgeSourceType }
              : { orgType: value.topic as OrgKnowledgeType }),
          });
        } else if (scope === "PRODUCT" && productId) {
          await api.createProductKnowledgeSource(productId, {
            sourceType: value.topic as KnowledgeSourceType,
            title: value.title,
            body: value.body,
            variantId: value.variantId,
          });
        } else {
          await api.createOrgKnowledge({
            knowledgeType: value.topic as OrgKnowledgeType,
            title: value.title,
            body: value.body,
            sourceUrl: null,
          });
        }
        setOpen(false);
        await onSaved();
      }}
      onCancel={() => setOpen(false)}
    />
  );
}
