#!/usr/bin/env bash
#
# Coupang first-connection + order-routine live-proof BOOTSTRAP. Mints a single opaque run id and a single
# opaque approval id for this run, and writes the shared run env that run-backend-local.sh and preflight.sh
# both read. The approval id is what the backend live-call interlock (CoupangLiveCallGuard) is armed with and
# what the operator's single-use "Seated and ready." grant binds to (docs/sellerops_live_approval_contract.md).
#
# Both ids are ENVIRONMENT identifiers, never a credential or auth token. Re-run this to start a fresh run —
# a new approval id invalidates the old one, so a stale approval can never be reused. NO Coupang call, no
# credential, no server started here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/current.env"

RUN_ID="cp-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
GIT_COMMIT="$(git -C "$HERE" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DB_ALIAS="${SELLEROPS_COUPANG_DB_ALIAS:-coupang_proof}"
BACKEND_ORIGIN="${SELLEROPS_COUPANG_BACKEND_ORIGIN:-http://127.0.0.1:18091}"
FRONTEND_ORIGIN="${SELLEROPS_COUPANG_FRONTEND_ORIGIN:-http://localhost:5173}"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/bootstrap.sh — shared run identity for backend + preflight. Do NOT commit.
COUPANG_RUN_ID=$RUN_ID
COUPANG_APPROVAL_ID=$APPROVAL_ID
COUPANG_GIT_COMMIT=$GIT_COMMIT
COUPANG_DB_ALIAS=$DB_ALIAS
COUPANG_BACKEND_ORIGIN=$BACKEND_ORIGIN
COUPANG_FRONTEND_ORIGIN=$FRONTEND_ORIGIN
ENV

echo "coupang live-proof bootstrap complete → $RUN_ENV"
echo
echo "  run id     : $RUN_ID"
echo "  approval id: $APPROVAL_ID  (arms the backend live-call interlock; binds the operator grant)"
echo "  git commit : $GIT_COMMIT"
echo "  db alias   : $DB_ALIAS"
echo "  backend    : $BACKEND_ORIGIN"
echo "  frontend   : $FRONTEND_ORIGIN"
echo
echo "next: run-backend-local.sh, then start the frontend, then preflight.sh (all read $RUN_ENV)."
echo "the operator enters the real Coupang credential in the frontend at: $FRONTEND_ORIGIN/connect/coupang"
