#!/usr/bin/env bash
#
# Coupang WING 고객문의 list-calibration BOOTSTRAP — mints the run identity for
# COUPANG_WING_INQUIRY_LIST_CALIBRATION (READ_ONLY).
#
#   tools/coupang-local/wing-inquiry-bootstrap.sh
#
# Its own script rather than an argument on the credential bootstrap, because the two runs stand in front of
# different things. That one stands in front of the seller's keys; this one stands in front of a page of their
# customers' messages. A shared entrypoint would make the wrong one reachable by a typo, and the disclosure the
# operator reads is the whole product of these scripts.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is read, and no credential/env secret is touched here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

PHASE="COUPANG_WING_INQUIRY_LIST_CALIBRATION"

# Overridable so a hermetic check can point it at a temp directory — the same reason the credential bootstrap
# allows it: running the REAL bootstrap must never be able to overwrite the operator's live run env.
RUN_DIR="${SELLEROPS_WING_INQUIRY_RUN_DIR:-$HERE/.run}"
RUN_ENV="$RUN_DIR/wing-inquiry-calibration.env"

# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

if ! DIRT="$(git_hardened status --porcelain 2>/dev/null)"; then
  echo "BOOTSTRAP FAIL — could not read git status. Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-inquiry-bootstrap.sh — run identity for $PHASE.
# Read by wing-inquiry-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_INQUIRY_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='$PHASE'
ENV

echo "coupang WING 고객문의 calibration bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : $PHASE"
echo "  what it does : looks for an id SellerOps already holds in href/id/data-* ONLY, and measures the"
echo "                 repeating structure around wherever it lands (no assumption about the row tag)"
echo "  buyer text   : NEVER LEAVES THE PAGE. Text is compared in-page to fixed Coupang status words and"
echo "                 reduced to a boolean; attribute values and class names are compared in-page too."
echo "                 What comes back is counts, tag names, and attribute KINDS."
echo "  replies      : NEVER. This run cannot post, and the phase declares no action that could."
echo
echo "next: export SELLEROPS_INQUIRY_TARGET_IDS=inquiryId:<digits>[,productId:<digits>]"
echo "      tools/coupang-local/wing-inquiry-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
