#!/usr/bin/env bash
#
# Coupang WING READ-ONLY selector-probe BOOTSTRAP (browser-only: no backend, no DB, no frontend).
#
# The WING selector probe (`collector/src/cli/probe-wing-issuance-selectors.ts`) opens the seller's dedicated
# Chrome window and MEASURES fixed-label match counts on the page the seller navigated to themselves. It needs
# none of the backend/DB/frontend environment the order-routine proof needs, so it gets its own two-step
# harness: this bootstrap mints the run identity, and `wing-probe-preflight.sh` prepares + displays the
# sanitized Approval Manifest (docs/sellerops_live_approval_contract.md §2).
#
# The identity is written under the EXACT variable names the tested manifest gate
# (`collector/src/cli/approval-manifest-cli.ts`) reads — WALKTHROUGH_RUN_ID / WALKTHROUGH_APPROVAL_ID /
# WALKTHROUGH_GIT_COMMIT — so no hand-typed env mapping sits between bootstrap and the manifest and can drift.
#
# The per-run PROBE SCOPE is fixed here too, because scope is part of what the operator approves: a scope
# change is a §1.6 scope change ⇒ re-bootstrap ⇒ a new approval id ⇒ the old grant is dead. The default is the
# delete-selector calibration scope (`delete`), which is the one target the WING deletion path still needs.
#
# Both ids are ENVIRONMENT identifiers, never a credential or auth token. NO browser is launched, NO Coupang
# call is made, and no credential/env secret is read here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/wing-probe.env"

# Git, with the ambient git environment stripped. GIT_DIR / GIT_WORK_TREE / GIT_CONFIG_* inherited from the
# caller would otherwise decide WHICH repository this identity describes — the same hardening the preflight
# applies to its drift check, so the two cannot be pointed at different repositories.
git_hardened() {
  env -u GIT_DIR -u GIT_WORK_TREE -u GIT_INDEX_FILE -u GIT_OBJECT_DIRECTORY \
      -u GIT_ALTERNATE_OBJECT_DIRECTORIES -u GIT_COMMON_DIR -u GIT_CEILING_DIRECTORIES \
      -u GIT_CONFIG_GLOBAL -u GIT_CONFIG_SYSTEM -u GIT_CONFIG_COUNT -u GIT_CONFIG_NOSYSTEM \
      git -C "$REPO_ROOT" "$@"
}

# Canonical WING probe targets live in collector/src/cli/coupang-wing-classifier.ts
# (WING_PROBE_TARGET_NAMES). This script does NOT decide which are valid — the manifest gate fails closed with
# WING_PROBE_TARGETS_MISMATCH on anything that is not a canonical subset. It DOES enforce the character shape,
# because this value is written into a file the preflight later sources: an unvalidated `$(…)` would execute.
PROBE_TARGETS="${SELLEROPS_WING_PROBE_TARGETS:-delete}"
if ! printf '%s' "$PROBE_TARGETS" | grep -qE '^[a-z_]+(,[a-z_]+)*$'; then
  echo "BOOTSTRAP FAIL — SELLEROPS_WING_PROBE_TARGETS must be a comma-separated list of lowercase target names."
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo unknown)"
# Freshness stamp. A prepared manifest is valid for the process/session that prepared it (contract §2
# `expiresAt: process-lifetime`); the preflight refuses an identity older than its TTL so a run env left over
# from a previous session cannot silently re-authorize a new one.
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
# Every value is single-quoted: the preflight sources this file, and the shapes above (hex ids, a short SHA,
# digits, a fixed phase, a validated target list) contain no quote character, so nothing here can expand.
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-probe-bootstrap.sh — run identity for the WING read-only selector
# probe. Read by wing-probe-preflight.sh and sourced into the probe run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_PROBE_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='COUPANG_WING_SELECTOR_PROBE'
SELLEROPS_WING_PROBE_TARGETS='$PROBE_TARGETS'
ENV

echo "coupang WING selector-probe bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT"
echo "  phase        : COUPANG_WING_SELECTOR_PROBE (READ_ONLY)"
echo "  probe targets: $PROBE_TARGETS"
echo
echo "next: tools/coupang-local/wing-probe-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
