#!/usr/bin/env bash
#
# Coupang WING open-API KEY-DELETION BOOTSTRAP — the DESTRUCTIVE sibling of wing-probe-bootstrap.sh.
#
# Mints the run identity for a `COUPANG_WING_KEY_DELETION` run and PINS the current HEAD commit to it. The
# pinning is the point: `wing-deletion-preflight.sh` and the two CLIs all refuse unless the running code is
# still exactly this commit with a clean tree, so a leftover run env from a consumed approval can never
# re-authorize a run against different code (contract §1.6 — a code change ⇒ the approval is `REVOKED`).
#
# The identity is written under the EXACT variable names the tested manifest gate
# (`collector/src/cli/approval-manifest-cli.ts`) reads — WALKTHROUGH_RUN_ID / WALKTHROUGH_APPROVAL_ID /
# WALKTHROUGH_GIT_COMMIT — so no hand-typed env mapping sits between bootstrap and the manifest and can drift.
#
# Unlike the probe bootstrap there is NO per-run scope to choose: the destructive phase's channel / account /
# surface / operation / action budget are pinned in the phase spec itself (`COUPANG_WING_KEY_DELETION_SCOPE`)
# and the gate refuses any deviation. Nothing about this run is configurable from the environment.
#
# Both ids are ENVIRONMENT identifiers, never a credential or auth token. NO browser is launched, NO Coupang
# call is made, NOTHING is deleted, and no credential/env secret is read here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/wing-deletion.env"

# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

# Refuse to pin an identity we cannot honestly pin. The preflight and both CLIs compare HEAD against this
# value, so an `unknown` SHA here would produce a run env that can only ever fail — better to say so now.
GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. A destructive run must pin the commit it will execute."
    exit 1 ;;
esac

# A destructive run must be bootstrapped from a CLEAN tree. The preflight checks this again (and so do both
# CLIs), but pinning a SHA that already does not describe the tree just defers a guaranteed refusal.
DIRT="$(git_hardened status --porcelain 2>/dev/null)"; DIRT_RC=$?
if [ "$DIRT_RC" != "0" ]; then
  echo "BOOTSTRAP FAIL — could not read git status (exit $DIRT_RC). Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: a destructive approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
# Freshness stamp. A prepared manifest is valid for the process/session that prepared it (contract §2
# `expiresAt: process-lifetime`); the preflight refuses an identity older than its TTL.
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
# Every value is single-quoted: the preflight sources this file, and the shapes above (hex ids, a short SHA,
# digits, a fixed phase literal) contain no quote character, so nothing here can expand.
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-deletion-bootstrap.sh — run identity for the DESTRUCTIVE Coupang WING
# open-API key-deletion run. Read by wing-deletion-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_DELETION_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='COUPANG_WING_KEY_DELETION'
ENV

echo "coupang WING key-DELETION bootstrap complete → $RUN_ENV"
echo
echo "  run id      : $RUN_ID"
echo "  approval id : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit  : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase       : COUPANG_WING_KEY_DELETION  (agent READ_ONLY; the OPERATOR performs the irreversible delete)"
echo
echo "  ⚠ This prepares a DESTRUCTIVE run. Nothing is deleted by bootstrap, preflight, or the agent —"
echo "    but the run it prepares guides YOU to permanently delete your WING open-API key."
echo
echo "next: tools/coupang-local/wing-deletion-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
