#!/usr/bin/env bash
#
# Coupang WING CREDENTIAL bootstrap — mints the run identity for ONE of the two credential phases.
#
#   tools/coupang-local/wing-credential-bootstrap.sh calibration   # COUPANG_WING_CREDENTIAL_CELL_CALIBRATION
#   tools/coupang-local/wing-credential-bootstrap.sh handoff       # COUPANG_WING_CREDENTIAL_HANDOFF
#
# The two are deliberately ONE script with a required argument rather than a shared default. They differ in the
# only way that matters — the calibration reads no value and the handoff reads three — and a default would make
# the more dangerous one reachable by omission. There is no default; an unrecognised argument refuses.
#
# **A grant for one is never a grant for the other.** Each phase mints its own approval id into its own run env,
# and both the preflight and the CLI refuse a phase that is not their own.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is issued or read, and no credential/env secret is touched here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

KIND="${1:-}"
case "$KIND" in
  calibration)
    PHASE="COUPANG_WING_CREDENTIAL_CELL_CALIBRATION"
    WHAT="agent measures WHICH CELL holds each key; it reads NO VALUE"
    ;;
  handoff)
    PHASE="COUPANG_WING_CREDENTIAL_HANDOFF"
    WHAT="agent READS 업체코드 / Access Key / Secret Key once and hands them to the SellerOps vault"
    ;;
  *)
    echo "BOOTSTRAP FAIL — say which phase: 'calibration' (reads no value) or 'handoff' (reads the three values)."
    echo "  There is no default. The two runs differ in exactly the way that would matter if one were assumed."
    exit 1 ;;
esac

# Overridable so a hermetic check can point it at a temp directory — the same reason the reveal bootstrap allows
# it: running the REAL bootstrap must never be able to overwrite the operator's live run env.
RUN_DIR="${SELLEROPS_WING_CREDENTIAL_RUN_DIR:-$HERE/.run}"
RUN_ENV="$RUN_DIR/wing-credential-$KIND.env"

# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

if ! DIRT="$(git_hardened status --porcelain 2>/dev/null)"; then
  echo "BOOTSTRAP FAIL — could not read git status. Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-credential-bootstrap.sh $KIND — run identity for $PHASE.
# Read by wing-credential-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_CREDENTIAL_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='$PHASE'
ENV

echo "coupang WING credential bootstrap complete ($KIND) → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : $PHASE"
echo "  what it does : $WHAT"
echo "  key issuance : NEVER — neither phase presses 발급 or 확인. The seller issues their own key."
echo
echo "next: tools/coupang-local/wing-credential-preflight.sh $KIND  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
