#!/usr/bin/env bash
#
# Coupang WING issuance-form REVEAL bootstrap (browser-only: no backend, no DB, no frontend).
#
# Mints the run identity for `COUPANG_WING_ISSUANCE_FORM_REVEAL` — the one step where SellerOps highlights the
# live-calibrated 발급 control and the OPERATOR presses it. The press is expected to open the API configuration
# step; that expectation is NOT confirmed, and the key is created only by a later 확인, which has no tooling.
#
# There is NO per-run scope to choose: the phase pins its own channel / account / surface / operation / budget,
# and the gate refuses any deviation. Nothing about this run is configurable from the environment.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is issued, and no credential/env secret is read here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/wing-reveal.env"

# The SHARED hardened git, not a local copy. This file had its own, and it was weaker in exactly the ways that
# matter: it UNSET the config-file variables instead of pinning them to /dev/null (so a prepared HOME re-opens
# the `core.excludesFile` hole), and it carried none of the `-c` flags — `status.showUntrackedFiles=normal`,
# `core.excludesFile=/dev/null`, `safe.directory`. A drifting second copy of this hardening is the thing
# wing-harness-common.sh exists to prevent, and `repo-identity.test.ts` only asserts the shared one.
# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

# Refuse to pin an identity we cannot honestly pin: the CLI compares HEAD against this SHA and a clean tree, so
# an unreadable HEAD would produce an approval that can never be honored. The hex shape is checked, not just
# emptiness — `rev-parse` can succeed and print something that is not a commit.
GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

# A real marketplace press must be bootstrapped from a CLEAN tree — the same rule as the destructive harness, and
# it was missing here. The preflight and the CLI both check it again, but pinning a SHA that already does not
# describe the tree just defers a guaranteed refusal, and leaves behind a run env that looks valid.
DIRT="$(git_hardened status --porcelain 2>/dev/null)"; DIRT_RC=$?
if [ "$DIRT_RC" != "0" ]; then
  echo "BOOTSTRAP FAIL — could not read git status (exit $DIRT_RC). Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-reveal-bootstrap.sh — run identity for the WING issuance-form REVEAL
# run. Read by wing-reveal-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_REVEAL_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='COUPANG_WING_ISSUANCE_FORM_REVEAL'
ENV

echo "coupang WING issuance-form REVEAL bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : COUPANG_WING_ISSUANCE_FORM_REVEAL (agent READ_ONLY; the OPERATOR presses 발급)"
echo "  key issuance : NOT performed by this run — the final 확인 has no tooling and no phase"
echo
echo "next: tools/coupang-local/wing-reveal-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
