#!/usr/bin/env bash
#
# Coupang WING 상품평 ACQUISITION bootstrap — mints the run identity for
# COUPANG_WING_REVIEW_ACQUISITION (READ_ONLY on the marketplace).
#
#   tools/coupang-local/wing-review-acquire-bootstrap.sh
#
# Its own script rather than a flag on wing-review-bootstrap.sh, and the reason is the whole difference between
# the two runs. That one stands in front of a measurement: it opens a window, counts, and prints integers, and
# its disclosure is written around "nothing your customers wrote leaves the page". This one COLLECTS — it takes
# the review bodies off the screen and stores them in SellerOps. A shared entrypoint would make the collecting
# run reachable by a typo from the counting one, under the counting one's promises.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is read, and no credential/env secret is touched here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

PHASE="COUPANG_WING_REVIEW_ACQUISITION"

# Overridable so a hermetic check can point it at a temp directory — running the REAL bootstrap must never be
# able to overwrite the operator's live run env.
RUN_DIR="${SELLEROPS_WING_REVIEW_RUN_DIR:-$HERE/.run}"
RUN_ENV="$RUN_DIR/wing-review-acquisition.env"

# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

if ! DIRT="$(git_hardened status --porcelain 2>/dev/null)"; then
  echo "BOOTSTRAP FAIL — could not read git status. Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-review-acquire-bootstrap.sh — run identity for $PHASE.
# Read by wing-review-acquire-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_REVIEW_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='$PHASE'
ENV

echo "coupang WING 상품평 ACQUISITION bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : $PHASE"
echo "  what it does : READS the reviews on the page you bring up and STORES them in SellerOps — body, rating,"
echo "                 등록일, 노출상품ID (옵션ID), and how many photos/videos the review itself carries."
echo "                 Columns are resolved from Coupang's own header words."
echo "  the buyer    : NOT COLLECTED. The 구매자/작성자 column is resolved ONLY so that it can be excluded; no"
echo "                 name is read, and no field exists on the wire, in the record, or in the database to"
echo "                 hold one. Photos and videos are COUNTED, never sourced. No HTML/DOM/screenshot is kept."
echo "  paging       : YOURS. SellerOps never turns a page. One press per page: you bring a page up, press, it"
echo "                 reads that page. A walk is 'complete' only when the pager itself shows its last page."
echo "  marketplace  : 0 actions. Nothing is clicked, typed, submitted, or navigated on WING."
echo
echo "required: export SELLEROPS_REVIEW_ACCOUNT_SLOT=<24 hex>   (which connection these reviews belong to)"
echo "          tools/coupang-local/wing-credential-mint-slot.sh prints it for a seller account"
echo "next    : tools/coupang-local/wing-review-acquire-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note    : re-running this bootstrap mints a NEW approval id — the previous grant is dead."
