#!/usr/bin/env bash
#
# Coupang WING READ-ONLY selector-probe BOOTSTRAP (browser-only: no backend, no DB, no frontend).
#
# The WING selector probe (`collector/src/cli/probe-wing-issuance-selectors.ts`) opens the seller's dedicated
# Chrome window and MEASURES fixed-label match counts on the page the seller navigated to themselves. It needs
# none of the backend/DB/frontend environment the order-routine proof needs, so it gets its own two-step
# harness: this bootstrap mints the run identity, and `wing-probe-preflight.sh` prepares + displays the
# sanitized Approval Manifest (docs/sellerops_live_approval_contract.md §2).
#
# The identity is written under the EXACT variable names the tested manifest gate
# (`collector/src/cli/approval-manifest-cli.ts`) reads — WALKTHROUGH_RUN_ID / WALKTHROUGH_APPROVAL_ID /
# WALKTHROUGH_GIT_COMMIT — so no hand-typed env mapping sits between bootstrap and the manifest and can drift.
#
# The per-run PROBE SCOPE is fixed here too, because scope is part of what the operator approves: a scope
# change is a §1.6 scope change ⇒ re-bootstrap ⇒ a new approval id ⇒ the old grant is dead. The default is the
# delete-selector calibration scope (`delete`), which is the one target the WING deletion path still needs.
#
# Both ids are ENVIRONMENT identifiers, never a credential or auth token. NO browser is launched, NO Coupang
# call is made, and no credential/env secret is read here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/wing-probe.env"

# Canonical WING probe targets live in collector/src/cli/coupang-wing-classifier.ts
# (WING_PROBE_TARGET_NAMES). This script does NOT re-validate them — the manifest gate fails closed with
# WING_PROBE_TARGETS_MISMATCH on anything that is not a non-empty canonical subset in canonical order.
PROBE_TARGETS="${SELLEROPS_WING_PROBE_TARGETS:-delete}"

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
GIT_COMMIT="$(git -C "$HERE" rev-parse --short HEAD 2>/dev/null || echo unknown)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-probe-bootstrap.sh — run identity for the WING read-only selector
# probe. Read by wing-probe-preflight.sh and sourced into the probe run itself. Do NOT commit.
WALKTHROUGH_RUN_ID=$RUN_ID
WALKTHROUGH_APPROVAL_ID=$APPROVAL_ID
WALKTHROUGH_GIT_COMMIT=$GIT_COMMIT
SELLEROPS_APPROVAL_PHASE=COUPANG_WING_SELECTOR_PROBE
SELLEROPS_WING_PROBE_TARGETS=$PROBE_TARGETS
ENV

echo "coupang WING selector-probe bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT"
echo "  phase        : COUPANG_WING_SELECTOR_PROBE (READ_ONLY)"
echo "  probe targets: $PROBE_TARGETS"
echo
echo "next: tools/coupang-local/wing-probe-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
