#!/usr/bin/env bash
#
# Coupang WING 상품평 LOCATE bootstrap — mints the run identity for
# COUPANG_WING_REVIEW_LOCATE (READ_ONLY on the marketplace, and on SellerOps).
#
#   tools/coupang-local/wing-review-locate-bootstrap.sh
#
# Its own script rather than a flag on wing-review-acquire-bootstrap.sh, and the reason is the whole difference
# between the two runs. That one COLLECTS — it takes review bodies off the screen and stores them. This one
# reads the same rows through the same reader and stores NOTHING: it compares them to one review the seller
# already has and draws a ring around the single row that matches. A shared entrypoint would make the
# collecting run reachable by a typo from the one that only looks.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is read, and no credential/env secret is touched here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

PHASE="COUPANG_WING_REVIEW_LOCATE"

# Overridable so a hermetic check can point it at a temp directory — running the REAL bootstrap must never be
# able to overwrite the operator's live run env.
RUN_DIR="${SELLEROPS_WING_REVIEW_RUN_DIR:-$HERE/.run}"
RUN_ENV="$RUN_DIR/wing-review-locate.env"

# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

if ! DIRT="$(git_hardened status --porcelain 2>/dev/null)"; then
  echo "BOOTSTRAP FAIL — could not read git status. Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-review-locate-bootstrap.sh — run identity for $PHASE.
# Read by wing-review-locate-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_REVIEW_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='$PHASE'
ENV

echo "coupang WING 상품평 LOCATE bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : $PHASE"
echo "  what it does : you press [쿠팡에서 보기] on ONE 상품평 in SellerOps; it READS the 상품평 목록 page you"
echo "                 have on screen and OUTLINES the single row that matches on product, option, date,"
echo "                 rating and the review body's fingerprint."
echo "  what it keeps: NOTHING. No review is stored on this path — this run has no handoff. No HTML/DOM/"
echo "                 screenshot is kept. The 구매자/작성자 column is resolved ONLY so it can be excluded."
echo "  exactness    : exactly one match, or nothing is outlined. Zero and two are both refusals."
echo "  paging       : YOURS. SellerOps never turns a page; while you page, it re-reads what is on screen."
echo "  marketplace  : 0 actions. Nothing is clicked, typed, submitted, or navigated on WING."
echo
echo "next    : tools/coupang-local/wing-review-locate-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note    : re-running this bootstrap mints a NEW approval id — the previous grant is dead."
