#!/usr/bin/env bash
#
# Coupang WING issuance-form REVEAL bootstrap (browser-only: no backend, no DB, no frontend).
#
# Mints the run identity for `COUPANG_WING_GUIDED_ISSUANCE_WALK` — the one step where SellerOps highlights the
# live-calibrated 발급 control and the OPERATOR presses it. The press is expected to open the API configuration
# step; that expectation is NOT confirmed, and the key is created only by a later 확인, which has no tooling.
#
# There is NO per-run scope to choose: the phase pins its own channel / account / surface / operation / budget,
# and the gate refuses any deviation. Nothing about this run is configurable from the environment.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is issued, and no credential/env secret is read here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
# Overridable so the hermetic selfcheck can point it at a temp directory. Without this the selfcheck's
# BOOTSTRAP_DIRTY case — which runs the REAL bootstrap — would write over the operator's live run env if the
# dirty-tree guard ever regressed, i.e. exactly when that case is doing its job: a fresh approval id would kill
# a pending grant and leave a run env whose approvalId no longer matches the displayed manifest.
RUN_DIR="${SELLEROPS_WING_REVEAL_RUN_DIR:-$HERE/.run}"
# Its OWN run-env path. Seeded from the reveal harness, this pointed at `wing-reveal.env`: bootstrapping a walk
# silently destroyed a prepared reveal run and vice versa. Cross-pickup was already refused by the phase gate —
# both preflights check the phase written into the file — but one harness overwriting another's run identity is
# a collision, not a safe fallback.
RUN_ENV="$RUN_DIR/wing-walk.env"

# The SHARED hardened git, not a local copy. This file had its own, and it was weaker in exactly the ways that
# matter: it UNSET the config-file variables instead of pinning them to /dev/null (so a prepared HOME re-opens
# the `core.excludesFile` hole), and it carried none of the `-c` flags — `status.showUntrackedFiles=normal`,
# `core.excludesFile=/dev/null`, `safe.directory`. A drifting second copy of this hardening is the thing
# wing-harness-common.sh exists to prevent, and `repo-identity.test.ts` only asserts the shared one.
# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

# Refuse to pin an identity we cannot honestly pin: the CLI compares HEAD against this SHA and a clean tree, so
# an unreadable HEAD would produce an approval that can never be honored. The hex shape is checked, not just
# emptiness — `rev-parse` can succeed and print something that is not a commit.
GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

# A real marketplace press must be bootstrapped from a CLEAN tree — the same rule as the destructive harness, and
# it was missing here. The preflight and the CLI both check it again, but pinning a SHA that already does not
# describe the tree just defers a guaranteed refusal, and leaves behind a run env that looks valid.
#
# `if ! DIRT=…`, not a bare assignment followed by `$?`: under `set -e` a failing command substitution in a
# plain assignment trips errexit BEFORE the status can be read, so the refusal below was unreachable and an
# unreadable `git status` exited 128 with no message at all. It still failed closed — but silently, and the
# branch the comment advertises could never run.
if ! DIRT="$(git_hardened status --porcelain 2>/dev/null)"; then
  echo "BOOTSTRAP FAIL — could not read git status. Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-walk-bootstrap.sh — run identity for the WING GUIDED ISSUANCE WALK
# run. Read by wing-walk-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_WALK_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='COUPANG_WING_GUIDED_ISSUANCE_WALK'
ENV

echo "coupang WING GUIDED ISSUANCE WALK bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : COUPANG_WING_GUIDED_ISSUANCE_WALK (agent READ_ONLY; the OPERATOR does every WING act)"
echo "  navigation   : the SELLER reaches WING; the agent never navigates (0 gotos, 0 clicks, 0 inputs)"
echo "  highlights   : ONLY the two live-calibrated controls. The purpose radios, 확인 and the consent boxes"
echo "                 are TEXT-GUIDED — measured but not promoted, so no ring is drawn at them"
echo "  key issuance : NOT performed. The walk RESTS in front of '약관 동의 및 Key 발급받기' and never presses it"
echo
echo "next: tools/coupang-local/wing-walk-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
