#!/usr/bin/env bash
#
# Coupang WING 상품평 structure-discovery BOOTSTRAP — mints the run identity for
# COUPANG_WING_REVIEW_STRUCTURE_DISCOVERY (READ_ONLY).
#
#   tools/coupang-local/wing-review-bootstrap.sh
#
# Its own script rather than an argument on another bootstrap, for the reason the 고객문의 one is: these scripts
# stand in front of different things. That one stands in front of a page of customers' questions; this one
# stands in front of a page of what they wrote about the seller's products, with their names and photos beside
# it. A shared entrypoint would make the wrong one reachable by a typo, and the disclosure the operator reads is
# the whole product of these scripts.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is read, and no credential/env secret is touched here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

PHASE="COUPANG_WING_REVIEW_STRUCTURE_DISCOVERY"

# Overridable so a hermetic check can point it at a temp directory — the same reason the other bootstraps allow
# it: running the REAL bootstrap must never be able to overwrite the operator's live run env.
RUN_DIR="${SELLEROPS_WING_REVIEW_RUN_DIR:-$HERE/.run}"
RUN_ENV="$RUN_DIR/wing-review-discovery.env"

# shellcheck source=./wing-harness-common.sh
. "$HERE/wing-harness-common.sh"

GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || echo "")"
case "$GIT_COMMIT" in
  ""|*[!0-9a-f]*)
    echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
    exit 1 ;;
esac

if ! DIRT="$(git_hardened status --porcelain 2>/dev/null)"; then
  echo "BOOTSTRAP FAIL — could not read git status. Refusing rather than assuming a clean tree."
  exit 1
fi
if [ -n "$DIRT" ]; then
  echo "BOOTSTRAP FAIL — working tree is dirty. Commit or stash first: the approval must name the code that will run."
  printf '%s\n' "$DIRT" | head -5 | sed 's/^/  | /'
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-review-bootstrap.sh — run identity for $PHASE.
# Read by wing-review-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_REVIEW_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='$PHASE'
ENV

echo "coupang WING 상품평 discovery bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT  (PINNED — the run refuses if HEAD moves or the tree goes dirty)"
echo "  phase        : $PHASE"
echo "  what it does : measures WHAT THE SCREEN IS — which repeating unit Coupang's own field words agree on,"
echo "                 whether a seller REPLY CONTROL exists, and what shape the rating / date / id columns"
echo "                 have. It has no review id to look for; Coupang publishes no review API."
echo "  reviews      : NEVER LEAVE THE PAGE. Review bodies, buyer names and product names are not read into"
echo "                 any returned field; photos and videos are COUNTED and never sourced. Page text is"
echo "                 compared in-page against fixed Coupang words and date/rating shape patterns, and only"
echo "                 counts, tag names and attribute kinds come back."
echo "  replies      : NEVER POSTED. This run cannot press a control, and the phase declares no action that"
echo "                 could. It only counts whether such a control exists."
echo
echo "optional: export SELLEROPS_REVIEW_PRODUCT_IDS=productId:<digits>[,sellerProductId:<digits>]"
echo "          (only for the catalog-scope question — the run measures the screen with or without it)"
echo "next    : tools/coupang-local/wing-review-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note    : re-running this bootstrap mints a NEW approval id — the previous grant is dead."
