#!/usr/bin/env bash
#
# Coupang WING issuance-form REVEAL bootstrap (browser-only: no backend, no DB, no frontend).
#
# Mints the run identity for `COUPANG_WING_ISSUANCE_FORM_REVEAL` — the one step where SellerOps highlights the
# live-calibrated 발급 control and the OPERATOR presses it. The press is expected to open the API configuration
# step; that expectation is NOT confirmed, and the key is created only by a later 확인, which has no tooling.
#
# There is NO per-run scope to choose: the phase pins its own channel / account / surface / operation / budget,
# and the gate refuses any deviation. Nothing about this run is configurable from the environment.
#
# Both ids are ENVIRONMENT identifiers, never a credential. NO browser is launched, NO Coupang call is made,
# NOTHING is issued, and no credential/env secret is read here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/wing-reveal.env"

# Git with the ambient git environment stripped — GIT_DIR / GIT_WORK_TREE / GIT_CONFIG_* inherited from the
# caller would otherwise decide WHICH repository this identity describes.
git_hardened() {
  env -u GIT_DIR -u GIT_WORK_TREE -u GIT_INDEX_FILE -u GIT_OBJECT_DIRECTORY \
      -u GIT_ALTERNATE_OBJECT_DIRECTORIES -u GIT_COMMON_DIR -u GIT_CEILING_DIRECTORIES \
      -u GIT_CONFIG_GLOBAL -u GIT_CONFIG_SYSTEM -u GIT_CONFIG_COUNT -u GIT_CONFIG_NOSYSTEM \
      -u GIT_CONFIG_PARAMETERS \
      git -C "$REPO_ROOT" "$@"
}

# Refuse to pin an identity we cannot honestly pin: the CLI compares HEAD against this SHA and a clean tree, so
# an unreadable HEAD would produce an approval that can never be honored.
GIT_COMMIT="$(git_hardened rev-parse --short HEAD 2>/dev/null || true)"
if [ -z "$GIT_COMMIT" ]; then
  echo "BOOTSTRAP FAIL — could not read HEAD in $REPO_ROOT. Refusing to mint an identity that cannot be verified."
  exit 1
fi

RUN_ID="wt-$(openssl rand -hex 6)"
APPROVAL_ID="apr-$(openssl rand -hex 6)"
BOOTSTRAP_EPOCH="$(date +%s)"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by tools/coupang-local/wing-reveal-bootstrap.sh — run identity for the WING issuance-form REVEAL
# run. Read by wing-reveal-preflight.sh and sourced into the run itself. Do NOT commit.
WALKTHROUGH_RUN_ID='$RUN_ID'
WALKTHROUGH_APPROVAL_ID='$APPROVAL_ID'
WALKTHROUGH_GIT_COMMIT='$GIT_COMMIT'
WING_REVEAL_BOOTSTRAP_EPOCH='$BOOTSTRAP_EPOCH'
SELLEROPS_APPROVAL_PHASE='COUPANG_WING_ISSUANCE_FORM_REVEAL'
ENV

echo "coupang WING issuance-form REVEAL bootstrap complete → $RUN_ENV"
echo
echo "  run id       : $RUN_ID"
echo "  approval id  : $APPROVAL_ID  (binds the operator's single-use grant)"
echo "  git commit   : $GIT_COMMIT"
echo "  phase        : COUPANG_WING_ISSUANCE_FORM_REVEAL (agent READ_ONLY; the OPERATOR presses 발급)"
echo "  key issuance : NOT performed by this run — the final 확인 has no tooling and no phase"
echo
echo "next: tools/coupang-local/wing-reveal-preflight.sh  (prepares + displays the Approval Manifest; no browser)"
echo "note: re-running this bootstrap mints a NEW approval id — the previous grant is dead."
