#!/usr/bin/env bash
#
# NAVER walkthrough BOOTSTRAP. Generates a single opaque walkthroughRunId for this run and writes the
# shared run env that the backend, the frontend, and the preflight all read — so the operator's tab can be
# proven bound to THIS exact backend/frontend/DB/runtime (the binding a green /health could not give).
#
# The run id is an ENVIRONMENT identifier, never a credential or auth token. Re-run this to start a fresh
# run (a new id invalidates the old one). NO NAVER call, no credential, no server started here.
#
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="$HERE/.run"
RUN_ENV="$RUN_DIR/current.env"

RUN_ID="wt-$(openssl rand -hex 6)"
# Opaque approval binding id (see docs/sellerops_live_approval_contract.md §2). Not a credential/token —
# it is the id the operator's single-use "Seated and ready." grant binds to. A fresh bootstrap mints a new
# one, so a stale approval can never be reused.
APPROVAL_ID="apr-$(openssl rand -hex 6)"
GIT_COMMIT="$(git -C "$HERE" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DB_ALIAS="${SELLEROPS_WALKTHROUGH_DB_ALIAS:-naver_walkthrough}"
FRONTEND_ORIGIN="${SELLEROPS_WALKTHROUGH_FRONTEND_ORIGIN:-http://localhost:5173}"
BACKEND_ORIGIN="${SELLEROPS_WALKTHROUGH_BACKEND_ORIGIN:-http://127.0.0.1:18090}"

mkdir -p "$RUN_DIR"
cat > "$RUN_ENV" <<ENV
# Generated by bootstrap.sh — shared run identity for backend + frontend + preflight. Do NOT commit.
WALKTHROUGH_RUN_ID=$RUN_ID
WALKTHROUGH_APPROVAL_ID=$APPROVAL_ID
WALKTHROUGH_GIT_COMMIT=$GIT_COMMIT
WALKTHROUGH_DB_ALIAS=$DB_ALIAS
WALKTHROUGH_FRONTEND_ORIGIN=$FRONTEND_ORIGIN
WALKTHROUGH_BACKEND_ORIGIN=$BACKEND_ORIGIN
ENV

echo "walkthrough bootstrap complete → $RUN_ENV"
echo
echo "  run id     : $RUN_ID"
echo "  approval id: $APPROVAL_ID"
echo "  git commit : $GIT_COMMIT"
echo "  db alias   : $DB_ALIAS"
echo "  frontend   : $FRONTEND_ORIGIN"
echo "  backend    : $BACKEND_ORIGIN"
echo
echo "next: run-backend-local.sh, then run-frontend-local.sh, then preflight.sh (all read $RUN_ENV)."
echo "operator URL will be: $FRONTEND_ORIGIN/connect/naver?walkthroughRun=$RUN_ID"
