"""Autogenerate-empty parity test: SQLAlchemy models vs baseline migration.

Applies the baseline Alembic migration to a temporary SQLite database, then
asks Alembic to compute the schema diff between that live DB and the
SQLAlchemy model metadata.  A passing test means the model layer reflects
the baseline DDL exactly — no spurious migrations would be generated by
``alembic revision --autogenerate`` against a fresh dev DB.

This is the gate that protects against silent model drift.  Any time a new
model column or table is added, the baseline (or a newer migration) must
match it or this test fails.

Skips cleanly when the SQLAlchemy / aiosqlite / alembic deps are not in the
active environment (the [saas] extras carry them; the [dev] extras do not
require them).
"""

from __future__ import annotations

import os
import pathlib
import subprocess
import tempfile

import pytest

# Hard skip when the SaaS-evolution deps are not installed.  Alembic is part
# of those extras; importorskip on alembic also gates this whole module.
pytest.importorskip("sqlalchemy")
pytest.importorskip("aiosqlite")
pytest.importorskip("alembic")

from sqlalchemy import Float, create_engine
from sqlalchemy.dialects.sqlite import REAL as SqliteREAL

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext

from src.voc.persistence.models import metadata as models_metadata


# Path to the repo root; alembic.ini lives here.
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]


def _compare_type(ctx, inspected_column, metadata_column, inspected_type, metadata_type):
    """Mirror of src/voc/persistence/alembic/env.py::_compare_type.

    Duplicated locally because env.py is a script invoked by Alembic at
    runtime (importing it would trigger ``context.run_migrations()`` with
    no context configured).  The canonical version is in env.py; if the
    rule needs to broaden, change both.
    """
    if ctx.dialect.name == "sqlite":
        if isinstance(inspected_type, SqliteREAL) and isinstance(metadata_type, Float):
            return False
    return None


def test_models_match_baseline_schema():
    """Baseline-applied SQLite schema must equal the SQLAlchemy model metadata."""
    with tempfile.TemporaryDirectory() as tmp:
        db_path = pathlib.Path(tmp) / "verify.db"
        env = {**os.environ, "DATABASE_URL": f"sqlite:///{db_path}"}

        # Apply the baseline migration to the temp DB.
        result = subprocess.run(
            ["alembic", "upgrade", "head"],
            cwd=str(_REPO_ROOT),
            env=env,
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, (
            f"alembic upgrade head failed (exit {result.returncode}):\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )

        # Compare the live DB schema against the model metadata.
        engine = create_engine(f"sqlite:///{db_path}")
        try:
            with engine.connect() as conn:
                mc = MigrationContext.configure(
                    conn, opts={"compare_type": _compare_type}
                )
                diffs = compare_metadata(mc, models_metadata)
        finally:
            engine.dispose()

        assert diffs == [], (
            "Schema drift between baseline migration and SQLAlchemy models. "
            f"Detected {len(diffs)} diff(s):\n"
            + "\n".join(f"  [{i}] {d!r}" for i, d in enumerate(diffs))
        )
