#!/usr/bin/env bash
# Overnight OliveYoung review collection + reporting runner.
#
# Resumable, auth-aware, and quality-gated. The heavy lifting
# (status classification, summary.json, summary.tsv,
# failed_products.csv) lives in `src/voc/app/overnight_batch.py`
# and is unit-tested. This script is a thin orchestrator: preflight,
# pipeline call, sleep, repeat.
#
# TSV authoring discipline
# ------------------------
# This runner does NOT write summary.tsv during the loop. Each
# `classify` call writes only a per-product sidecar JSON (and a
# best-effort `progress.tsv` for live tailing). At end-of-batch
# `finalize` regenerates `summary.tsv` from sidecars atomically and
# validates that every row has the 9-field invariant. This removes
# the bash↔python TSV-write boundary that produced shifted columns
# in earlier runs.
#
# Inputs
#   $1                     CSV path (4-col canonical input or 8-col
#                          failed_products.csv resume file).
#                          Default: data/batch_inputs/oy_top8_interview_real.csv
#
# Environment
#   MAX_REVIEWS_PER_SORT       integer cap per signal sort. Default 200.
#                              (5 sorts × cap = theoretical raw cap.)
#   ON_AUTH_FAILURE            stop_batch | skip_product. Default skip_product.
#   STOP_AFTER_AUTH_FAILURES   integer N — stop the batch after N consecutive
#                              auth/anti-bot failures. Default 2.
#   PRODUCT_SLEEP_MIN_SECS     min sleep between products. Default 90.
#   PRODUCT_SLEEP_MAX_SECS     max sleep between products. Default 180.
#   STUB_LLM                   pass-through for smoke runs.
#   CDP_ENDPOINT               CDP endpoint. Default http://127.0.0.1:9222.
#   BATCH_REPO_ROOT            repo root to cd into. Default this file's repo.
#                              Tests override to point at a sandbox.
#   PIPELINE_SCRIPT            path to run_phase2e_pipeline.py. Tests stub.
#   REPUBLISH_SCRIPT           path to republish_run.py. Tests stub.
#   INSPECT_SCRIPT             path to inspect_run_quality.py. Tests stub.
#   SKIP_CDP_PREFLIGHT         "1" to skip CDP preflight. Tests use this.
#   SKIP_OPENAI_KEY_CHECK      "1" to skip OpenAI key check. Tests use this.
#
# Outputs
#   logs/batch_runs/<BATCH_ID>/
#     master.log
#     summary.tsv              authoritative; regenerated by finalize.
#                              Header + one row per product, each row
#                              has exactly 9 tab-separated fields.
#     summary.json             aggregated counts + per-product details
#     progress.tsv             live append from classify (best-effort)
#     failed_products.csv      resumable subset (auth/anti_bot/pipeline_failed
#                              /insufficient_corpus)
#     products/<rank>_<goodsNo>.json   per-product outcome sidecar
#     <rank>_<goodsNo>_<slug>.log      per-product pipeline log
set -u

REPO_ROOT="${BATCH_REPO_ROOT:-/Users/taewookang/Downloads/workspace/aiagent}"
cd "$REPO_ROOT"

CSV="${1:-data/batch_inputs/oy_top8_interview_real.csv}"
BATCH_ID="${BATCH_ID:-oy_top8_real_$(date +%Y%m%d_%H%M%S)}"
LOG_DIR="logs/batch_runs/$BATCH_ID"
mkdir -p "$LOG_DIR/products"

# Tunables ----------------------------------------------------------------
MAX_REVIEWS_PER_SORT="${MAX_REVIEWS_PER_SORT:-200}"
ON_AUTH_FAILURE="${ON_AUTH_FAILURE:-skip_product}"   # stop_batch | skip_product
STOP_AFTER_AUTH_FAILURES="${STOP_AFTER_AUTH_FAILURES:-2}"
PRODUCT_SLEEP_MIN_SECS="${PRODUCT_SLEEP_MIN_SECS:-90}"
PRODUCT_SLEEP_MAX_SECS="${PRODUCT_SLEEP_MAX_SECS:-180}"
CDP_ENDPOINT="${CDP_ENDPOINT:-http://127.0.0.1:9222}"
PIPELINE_SCRIPT="${PIPELINE_SCRIPT:-scripts/run_phase2e_pipeline.py}"
REPUBLISH_SCRIPT="${REPUBLISH_SCRIPT:-scripts/republish_run.py}"
INSPECT_SCRIPT="${INSPECT_SCRIPT:-scripts/inspect_run_quality.py}"
STUB_LLM_FLAG=""
if [ "${STUB_LLM:-}" = "1" ]; then STUB_LLM_FLAG="--stub-llm"; fi

set -a
# .env is optional in some test/dev setups.
if [ -f .env ]; then source .env; fi
set +a

MASTER_LOG="$LOG_DIR/master.log"
SUMMARY="$LOG_DIR/summary.tsv"
# Note: summary.tsv is NOT written here. finalize regenerates it from
# sidecars at end-of-batch. progress.tsv is the in-loop tail target.

CONSECUTIVE_AUTH_FAILURES=0
STOP_BATCH=0
FINAL_EXIT=0

{
  echo "BATCH_ID=$BATCH_ID"
  echo "CSV=$CSV"
  echo "LOG_DIR=$LOG_DIR"
  echo "MAX_REVIEWS_PER_SORT=$MAX_REVIEWS_PER_SORT"
  echo "ON_AUTH_FAILURE=$ON_AUTH_FAILURE"
  echo "STOP_AFTER_AUTH_FAILURES=$STOP_AFTER_AUTH_FAILURES"
  echo "PRODUCT_SLEEP=${PRODUCT_SLEEP_MIN_SECS}..${PRODUCT_SLEEP_MAX_SECS}s"
  echo "CDP_ENDPOINT=$CDP_ENDPOINT"
  echo "started_at=$(date '+%Y-%m-%d %H:%M:%S')"

  # Initial CDP smoke check — fail fast if Chrome debug isn't up.
  if [ "${SKIP_CDP_PREFLIGHT:-0}" != "1" ]; then
    if ! curl -s -m 5 "${CDP_ENDPOINT}/json/version" >/dev/null; then
      echo "ERROR: CDP endpoint not reachable: $CDP_ENDPOINT"
      exit 1
    fi
  fi

  if [ "${SKIP_OPENAI_KEY_CHECK:-0}" != "1" ]; then
    if [ -z "${OPENAI_API_KEY:-}" ] && [ "${STUB_LLM:-}" != "1" ]; then
      echo "ERROR: OPENAI_API_KEY missing (set STUB_LLM=1 for smoke runs)"
      exit 1
    fi
  fi

  # Read the CSV using csv-mode awk-equivalent: trust the file's
  # first 4 columns as rank,profile,goodsNo,slug. Wider rows
  # (failed_products.csv) are accepted because we only consume those
  # 4 columns; extras are ignored.
  tail -n +2 "$CSV" | while IFS=, read -r rank profile goodsNo slug rest; do
    [ -z "$goodsNo" ] && continue
    [ -z "$rank" ] && continue

    if [ "$STOP_BATCH" -eq 1 ]; then
      echo ""
      echo "[$rank] $slug — skipped (batch stopped after auth failures)"
      python3 -m src.voc.app.overnight_batch classify \
        --batch-dir "$LOG_DIR" \
        --rank "$rank" --profile "$profile" --goodsNo "$goodsNo" --slug "$slug" \
        --run-dir "outputs/_skipped_${BATCH_ID}_${rank}_${slug}" \
        --pipeline-exit 999 --republish-exit 999 --inspect-exit 999 \
        --skipped >/dev/null
      continue
    fi

    PRODUCT_URL="https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=${goodsNo}"
    RUN_DIR="outputs/batch_${BATCH_ID}_${rank}_${profile}_${slug}"
    PRODUCT_LOG="$LOG_DIR/${rank}_${goodsNo}_${slug}.log"

    echo ""
    echo "======================================================================"
    echo "[$rank] $slug / $goodsNo / $profile"
    echo "PRODUCT_URL=$PRODUCT_URL"
    echo "RUN_DIR=$RUN_DIR"
    echo "LOG=$PRODUCT_LOG"
    echo "started_at=$(date '+%Y-%m-%d %H:%M:%S')"
    echo "======================================================================"

    mkdir -p "$RUN_DIR/shared" "$RUN_DIR/seller_report"

    # ------- Per-product preflight ---------------------------------------
    # CDP /json/version every product. If Chrome was killed mid-batch
    # (e.g. operator closed it), we want to mark this product as
    # preflight_failed and either stop or skip per ON_AUTH_FAILURE.
    PREFLIGHT_OK=1
    if [ "${SKIP_CDP_PREFLIGHT:-0}" != "1" ]; then
      if ! curl -s -m 5 "${CDP_ENDPOINT}/json/version" >/dev/null; then
        echo "  ⚠ CDP unreachable — marking preflight_failed"
        PREFLIGHT_OK=0
      fi
    fi

    PIPE_EXIT=999
    REPUB_EXIT=999
    INSPECT_EXIT=999

    if [ "$PREFLIGHT_OK" -eq 1 ]; then
      PYTHONPATH=. python3 "$PIPELINE_SCRIPT" \
        "$PRODUCT_URL" \
        --multi-sort \
        --corpus-mode observable_multi_sort \
        --max-reviews all \
        --max-reviews-per-sort "$MAX_REVIEWS_PER_SORT" \
        --category-mode full_path \
        --cdp-endpoint "$CDP_ENDPOINT" \
        $STUB_LLM_FLAG \
        --emit-analysis-report-json "$RUN_DIR/shared/analysis_report.json" \
        --emit-collection-summary-json "$RUN_DIR/shared/collection_summary.json" \
        --analysis-report-source-url "$PRODUCT_URL" \
        --out-pdf "$RUN_DIR/seller_report/seller_report_ko.pdf" \
        > "$PRODUCT_LOG" 2>&1
      PIPE_EXIT=$?

      if [ "$PIPE_EXIT" -eq 0 ]; then
        PYTHONPATH=. python3 "$REPUBLISH_SCRIPT" --run-dir "$RUN_DIR" \
          >> "$PRODUCT_LOG" 2>&1
        REPUB_EXIT=$?

        PYTHONPATH=. python3 "$INSPECT_SCRIPT" --run-dir "$RUN_DIR" \
          >> "$PRODUCT_LOG" 2>&1
        INSPECT_EXIT=$?
      fi
    fi

    # ------- Classify: write sidecar JSON + progress.tsv -----------------
    # NOTE: classify does NOT touch summary.tsv. finalize regenerates
    # summary.tsv from sidecars at end-of-batch.
    PREFLIGHT_FLAG=""
    if [ "$PREFLIGHT_OK" -eq 0 ]; then PREFLIGHT_FLAG="--preflight-failed"; fi

    CLASSIFY_OUT=$(python3 -m src.voc.app.overnight_batch classify \
      --batch-dir "$LOG_DIR" \
      --rank "$rank" --profile "$profile" --goodsNo "$goodsNo" --slug "$slug" \
      --run-dir "$RUN_DIR" \
      --pipeline-exit "$PIPE_EXIT" \
      --republish-exit "$REPUB_EXIT" \
      --inspect-exit "$INSPECT_EXIT" \
      --log-path "$PRODUCT_LOG" \
      $PREFLIGHT_FLAG)
    PRODUCT_STATUS=$(echo "$CLASSIFY_OUT" | python3 -c \
      "import json,sys;print(json.loads(sys.stdin.read())['status'])")

    echo "  → status=$PRODUCT_STATUS pipeline=$PIPE_EXIT republish=$REPUB_EXIT inspect=$INSPECT_EXIT"
    echo "  → sidecar written to $LOG_DIR/products/${rank}_${goodsNo}.json"

    # ------- Auth-failure escalation -------------------------------------
    case "$PRODUCT_STATUS" in
      auth_required|anti_bot_pause_required|preflight_failed)
        CONSECUTIVE_AUTH_FAILURES=$((CONSECUTIVE_AUTH_FAILURES + 1))
        echo "  ⚠ auth/anti-bot bucket — consecutive=$CONSECUTIVE_AUTH_FAILURES"
        if [ "$ON_AUTH_FAILURE" = "stop_batch" ]; then
          echo "  ⚠ ON_AUTH_FAILURE=stop_batch — halting after this product"
          STOP_BATCH=1
        elif [ "$CONSECUTIVE_AUTH_FAILURES" -ge "$STOP_AFTER_AUTH_FAILURES" ]; then
          echo "  ⚠ STOP_AFTER_AUTH_FAILURES=$STOP_AFTER_AUTH_FAILURES reached — halting"
          STOP_BATCH=1
        fi
        ;;
      *)
        CONSECUTIVE_AUTH_FAILURES=0
        ;;
    esac

    echo "finished_at=$(date '+%Y-%m-%d %H:%M:%S') status=$PRODUCT_STATUS"

    # Sleep with jitter (skip if we just decided to stop the batch).
    if [ "$STOP_BATCH" -ne 1 ]; then
      JITTER_RANGE=$((PRODUCT_SLEEP_MAX_SECS - PRODUCT_SLEEP_MIN_SECS + 1))
      [ "$JITTER_RANGE" -lt 1 ] && JITTER_RANGE=1
      SLEEP_SECS=$((PRODUCT_SLEEP_MIN_SECS + RANDOM % JITTER_RANGE))
      echo "sleeping ${SLEEP_SECS}s before next product..."
      sleep "$SLEEP_SECS"
    fi
  done

  # ------- Finalize: regenerate summary.tsv + summary.json + failed_csv --
  echo ""
  echo "BATCH COMPLETE"
  echo "finished_at=$(date '+%Y-%m-%d %H:%M:%S')"
  if ! python3 -m src.voc.app.overnight_batch finalize \
        --batch-dir "$LOG_DIR" \
        --batch-id "$BATCH_ID" \
        --requested-max-reviews-per-sort "$MAX_REVIEWS_PER_SORT"; then
    echo "ERROR: finalize reported validation errors"
    FINAL_EXIT=3
  fi

  # ------- Belt-and-suspenders: awk 9-field check on summary.tsv --------
  # finalize already validates this internally and exits nonzero on
  # failure, but we re-check at the bash level so the master.log
  # surfaces a single, grep-able VALIDATION_ERROR line operators can
  # spot at a glance.
  if [ -f "$SUMMARY" ]; then
    BAD=$(awk -F'\t' 'NF != 9 {print "  line " NR " has " NF " fields: " $0}' "$SUMMARY")
    if [ -n "$BAD" ]; then
      echo "VALIDATION_ERROR: summary.tsv has rows with field count != 9"
      echo "$BAD"
      FINAL_EXIT=3
    fi
    ROW_COUNT=$(awk 'END{print NR}' "$SUMMARY")
    echo "summary.tsv: $ROW_COUNT line(s) (1 header + N products), all 9 fields"
  else
    echo "VALIDATION_ERROR: $SUMMARY not produced by finalize"
    FINAL_EXIT=3
  fi

  echo "SUMMARY=$SUMMARY"
  echo ""
  if [ -f "$SUMMARY" ]; then cat "$SUMMARY"; fi
} | tee "$MASTER_LOG"

exit $FINAL_EXIT
